{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\",\"CalcGroup\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"2. Summary\",\"Dim: Events\",\"Dim: Tickets\",\"Fact: Orders\",\"Dim: Customers\",\"Dim: Calendar\",\"5. Color\",\"Param: Summary Metrics Slicer\",\"6. SVG Image\",\"Param: Day Period Slicer\",\"7. Title & Subtitle\",\"3. Sales\",\"4  Customers\",\"1. Core Measures\",\"Param: Daily moving average\",\"Param: Sales metrics slicer\",\"Param: Monthly moving average\",\"Dim: Ticket phase\",\"Param: Scatter Cluster Color\",\"Param: Scatter Legends\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Measures"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Dimension tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Fact tables"
      }
    ],
    "relationships": [
      {
        "name": "9c909159-a71f-4a58-8993-41efd6dae09f",
        "fromColumn": "ticketID",
        "fromTable": "Fact: Orders",
        "toColumn": "id",
        "toTable": "Dim: Tickets"
      },
      {
        "name": "547e3dfa-5e9c-4b5b-9234-04e461e0815b",
        "fromColumn": "eventID",
        "fromTable": "Fact: Orders",
        "toColumn": "id",
        "toTable": "Dim: Events"
      },
      {
        "name": "073fe431-e432-efa8-3eb2-47288fdc8fb0",
        "fromColumn": "customerID",
        "fromTable": "Fact: Orders",
        "toColumn": "id",
        "toTable": "Dim: Customers"
      },
      {
        "name": "0ebb2482-bfdc-49a0-920a-f1ad456c2799",
        "fromColumn": "lastLoginDateID",
        "fromTable": "Dim: Customers",
        "isActive": false,
        "toColumn": "dateID",
        "toTable": "Dim: Calendar"
      },
      {
        "name": "c2f82735-6e37-40e7-af85-7c6c6890dafa",
        "fromColumn": "creationDateID",
        "fromTable": "Dim: Customers",
        "isActive": false,
        "toColumn": "dateID",
        "toTable": "Dim: Calendar"
      },
      {
        "name": "92779d46-9223-4ff0-8daf-91545d33d9cc",
        "fromColumn": "group",
        "fromTable": "Param: Sales metrics",
        "toColumn": "order",
        "toTable": "Param: Sales metrics slicer"
      },
      {
        "name": "AutoDetected_0f0f0284-7917-45e2-a993-ec675a9ca6ac",
        "fromColumn": "phaseID",
        "fromTable": "Dim: Tickets",
        "toColumn": "phaseID",
        "toTable": "Dim: Ticket phase"
      },
      {
        "name": "526f7534-e85a-aa9f-7260-68cc116c4d86",
        "fromColumn": "cluster",
        "fromTable": "Param: Scatter Legends",
        "toColumn": "Order",
        "toTable": "Param: Scatter Cluster Color"
      },
      {
        "name": "691b0508-2071-868c-d2f9-66f55d16af46",
        "fromColumn": "creationDateID",
        "fromTable": "Fact: Orders",
        "toColumn": "dateID",
        "toTable": "Dim: Calendar"
      },
      {
        "name": "aa75a89d-d2e1-4106-9ed7-627a1698ce32",
        "fromColumn": "Group",
        "fromTable": "Param: Summary Metrics",
        "toColumn": "Group",
        "toTable": "Param: Summary Metrics Slicer"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "2. Summary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "55cca059-02aa-4b0c-9216-078cf9e582df",
        "measures": [
          {
            "name": "Filter: Date Slicer",
            "displayFolder": "7. Filter",
            "expression": [
              "",
              "CALCULATE(",
              "    INT( SELECTEDVALUE( 'Dim: Calendar'[dateID] ) IN ALL( 'Fact: Orders'[creationDateID] ) ),",
              "USERELATIONSHIP( 'Dim: Calendar'[dateID], 'Fact: Orders'[creationDateID] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ed580822-d616-44c3-92e2-9475bb36a858"
          },
          {
            "name": "Profit: Previous Year",
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "9a1816f5-a096-4c57-83f7-8d5ea4d344ca"
          },
          {
            "name": "Profit: Previous Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              ")"
            ],
            "lineageTag": "54ef6a49-1e45-4a44-a711-f8ecbb3a25f8"
          },
          {
            "name": "Profit: vs PD Reference Label",
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "VAR dodChange = [Profit] - [Profit: Previous Day]",
              "VAR changePercentage = DIVIDE( [Profit] - [Profit: Previous Day] , [Profit: Previous Day] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR Callout =",
              "SWITCH(",
              "    TRUE(),",
              "    ABS(dodChange) < 1000000, FORMAT( ABS(dodChange),  \"$#,.0K\" ),",
              "    ABS(dodChange) < 1000000000, FORMAT( ABS(dodChange),  \"$#,,.00M\" ),",
              "    ABS(dodChange) >= 1000000000, FORMAT( ABS(dodChange), \"$#,,,.00B\" )",
              ")",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & Callout & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & Callout & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "0fa92cc9-84e3-4d32-b3cc-71fbef58a3c9"
          },
          {
            "name": "Profit: vs PY Reference Label",
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "VAR yoyChange = [Profit] - [Profit: Previous Year]",
              "VAR changePercentage = DIVIDE( [Profit] - [Profit: Previous Year] , [Profit: Previous Year] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR Callout =",
              "SWITCH(",
              "    TRUE(),",
              "    ABS(yoyChange) < 1000000, FORMAT( ABS(yoyChange),  \"$#,.0K\" ),",
              "    ABS(yoyChange) < 1000000000, FORMAT( ABS(yoyChange),  \"$#,,.00M\" ),",
              "    ABS(yoyChange) >= 1000000000, FORMAT( ABS(yoyChange), \"$#,,,.00B\" )",
              ")",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & Callout & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & Callout & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "1792e61c-5109-4d55-9016-74e2497f42da"
          },
          {
            "name": "Tickets: Previous Year",
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [Tickets],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "605c191b-334d-4fb1-84d2-1127b64bb1cf"
          },
          {
            "name": "Orders: Previous Year",
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Complete Orders],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "93b58f33-2ce0-40ae-af50-6799ae5b4646"
          },
          {
            "name": "Tickets: Previous Day",
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [Tickets],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c5c9bc06-9ca3-4f15-9ca4-32a223de93b1"
          },
          {
            "name": "Orders: Previous Day",
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Complete Orders],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "808bf3db-c85a-4190-9386-93131d0ed300"
          },
          {
            "name": "Tickets: vs PD Reference Label",
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "VAR dodChange = [Tickets] - [Tickets: Previous Day]",
              "VAR changePercentage = DIVIDE( [Tickets] - [Tickets: Previous Day] , [Tickets: Previous Day] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\", ",
              "    changePercentage = 0 , \"—\" & whiteSpace,",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "959f3682-daea-4b8f-9ba4-b1b884a00144"
          },
          {
            "name": "Tickets: vs PY Reference Label",
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "VAR yoyChange = [Tickets] - [Tickets: Previous Year]",
              "VAR changePercentage = DIVIDE( [Tickets] - [Tickets: Previous Year] , [Tickets: Previous Year] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\",",
              "    changePercentage = 0 , \"—\" & whiteSpace,",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "32556174-e42f-4c2a-8889-ae8f6bb27acd"
          },
          {
            "name": "Orders: vs PD Reference Label",
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "VAR dodChange = [Complete Orders] - [Orders: Previous Day]",
              "VAR changePercentage = DIVIDE( [Complete Orders] - [Orders: Previous Day] , [Orders: Previous Day] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "883d197a-0b28-42e1-bb12-aabd39ebf43c"
          },
          {
            "name": "Orders: vs PY Reference Label",
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "VAR yoyChange = [Complete Orders] - [Orders: Previous Year]",
              "VAR changePercentage = DIVIDE( [Complete Orders] - [Orders: Previous Year] , [Orders: Previous Year] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "df0dae53-ae02-4b9c-9558-7152bf1beccb"
          },
          {
            "name": "New Customers: Previous Year",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "CALCULATE(",
              "    [New Customers],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "35b9c513-864a-4578-9d89-6c8dbfd1119d"
          },
          {
            "name": "New Customers: Previous Day",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "CALCULATE(",
              "    [New Customers],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f8b53097-2bfb-4ff3-ac00-9d7a009968f2"
          },
          {
            "name": "New Customers: vs PD Reference Label",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "VAR dodChange = [New Customers] - [New Customers: Previous Day]",
              "VAR changePercentage = DIVIDE( [New Customers] - [New Customers: Previous Day] , [New Customers: Previous Day] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\" & \" vs previous day\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\" & \" vs previous day\"",
              ")",
              "RETURN",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( dodChange, \"#,#\" ) & \")\"",
              ")"
            ],
            "lineageTag": "cdad7ab8-f022-4591-b1da-3a194ffda87e"
          },
          {
            "name": "New Customers: vs PY Reference Label",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "VAR yoyChange = [New Customers] - [New Customers: Previous Year]",
              "VAR changePercentage = DIVIDE( [New Customers] - [New Customers: Previous Year] , [New Customers: Previous Year] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\" & \" vs same period last year\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\" & \" vs same period last year\"",
              ")",
              "RETURN",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( yoyChange, \"#,#\" ) & \")\"",
              ")"
            ],
            "lineageTag": "6352eaef-4d56-4077-82bc-6ab7342397c4"
          },
          {
            "name": "Profit Margin: Previous Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit Margin],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              ")"
            ],
            "lineageTag": "e86f445e-6db8-4efa-a644-90f2666348c7"
          },
          {
            "name": "Profit Margin: Previous Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit Margin],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR ) ",
              ")"
            ],
            "lineageTag": "7fdad171-341c-404d-b75a-2b8fe80a48f0"
          },
          {
            "name": "Profit Margin: vs PD Reference Label",
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "VAR dodChange = [Profit Margin] - [Profit Margin: Previous Day]",
              "VAR changePercentage = DIVIDE( [Profit Margin] - [Profit Margin: Previous Day] , [Profit Margin: Previous Day] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( dodChange, \"0.0%\" ) & \" vs same period last year\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(dodChange), \"0.0%\" ) & \" vs same period last year\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "62911e24-a826-4f6d-9833-0b35b37d59d9"
          },
          {
            "name": "Profit Margin: vs PY Reference Label",
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "VAR yoyChange = [Profit Margin] - [Profit Margin: Previous Year] ",
              "VAR changePercentage = DIVIDE( [Profit Margin] - [Profit Margin: Previous Year] , [Profit Margin: Previous Year] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( yoyChange, \"0.0%\" ) & \" vs same period last year\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(yoyChange), \"0.0%\" ) & \" vs same period last year\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "a63f123e-7b4e-415b-9d4a-ce93e8fd137a"
          },
          {
            "name": "AVG Tickets per Order: Previous Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [AVG Tickets per Order],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              ")"
            ],
            "lineageTag": "ffaee9d7-49d7-45ff-a2d9-4dbf12b9cb46"
          },
          {
            "name": "AVG Tickets per Order: Previous Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    [AVG Tickets per Order],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR ) ",
              ")"
            ],
            "lineageTag": "e5189ea4-e133-4041-ab57-bec2a8172dfb"
          },
          {
            "name": "AVG Tickets per Order: vs PD Reference Label",
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [AVG Tickets per Order] - [AVG Tickets per Order: Previous Day] , [AVG Tickets per Order: Previous Day] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ), ",
              "    changePercentage = 0 , \"—\" & whiteSpace,",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" )",
              ")",
              "RETURN result"
            ],
            "lineageTag": "bd28f7fb-ca53-4036-b888-62cd1e9e4167"
          },
          {
            "name": "AVG Tickets per Order: vs PY Reference Label",
            "displayFolder": "2. KPI - Tickets",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [AVG Tickets per Order] - [AVG Tickets per Order: Previous Year] , [AVG Tickets per Order: Previous Year] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ), ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" )",
              ")",
              "RETURN result"
            ],
            "lineageTag": "6b93ad66-828c-409e-afe3-a85e33c8bba0"
          },
          {
            "name": "Completion %: Previous Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "\tCALCULATE(",
              "    [Completion Rate],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              "\t)"
            ],
            "lineageTag": "15321fc7-e78f-4af6-bded-c32ffffe1a04"
          },
          {
            "name": "Completion %: Previous Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "\tCALCULATE(",
              "    [Completion Rate],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR ) ",
              "\t)"
            ],
            "lineageTag": "93f94eae-fc0b-40c9-920d-84174b2fd9c7"
          },
          {
            "name": "Completion %: vs PY Reference Label",
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "VAR yoyChange = [Completion Rate] - [Completion %: Previous Year]",
              "VAR changePercentage = DIVIDE( [Completion Rate] - [Completion %: Previous Year] , [Completion %: Previous Year] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( yoyChange, \"0.0%\" ) & \" vs same period last year\" & \" (\" & FORMAT( [Completion %: Previous Year], \"0.0%\" ) & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(yoyChange), \"0.0%\" ) & \" vs same period last year\" & \" (\" & FORMAT( [Completion %: Previous Year], \"0.0%\" ) & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "8ae4f483-49c4-47d0-b3a6-9b9f2bbe9b22"
          },
          {
            "name": "Completion %: vs PD Reference Label",
            "displayFolder": "1. KPI - Orders",
            "expression": [
              "",
              "VAR dodChange = [Completion Rate] - [Completion %: Previous Day]",
              "VAR changePercentage = DIVIDE( [Completion Rate] - [Completion %: Previous Day] , [Completion %: Previous Day] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( dodChange, \"0.0%\" ) & \" vs than previous day\" & \" (\" & FORMAT( [Completion %: Previous Day], \"0.0%\" ) & \")\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(dodChange), \"0%\" ) & \" vs than previous day\" & \" (\" & FORMAT( [Completion %: Previous Day], \"0.0%\" ) & \")\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "214b15bd-a8aa-4e59-8b59-ef8e4e377679"
          },
          {
            "name": "Total New Customers Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "VAR CustomerTM = VALUES( 'Fact: Orders'[customerID] )",
              "VAR PriorCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Dim: Calendar'[dateID] ) ",
              "    )",
              ")",
              "VAR Result = ",
              "CALCULATE( ",
              "    [Profit],",
              "    EXCEPT( CustomerTM, PriorCustomers )",
              ")",
              "RETURN Result"
            ],
            "lineageTag": "8e2cf5cb-025c-47b8-a0cb-812bdaaad23c"
          },
          {
            "name": "AVG New Customers Value",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "DIVIDE( [Total New Customers Value], [New Customers], 0 )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b55f3d24-787f-4191-95d5-ac859a988584"
          },
          {
            "name": "AVG New Customers Value: Previous Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "CALCULATE(",
              "[AVG New Customers Value],",
              "DATEADD( 'Dim: Calendar'[date] , -1, DAY )",
              ")"
            ],
            "lineageTag": "4798da5c-1d9a-4b53-b052-27d11f1b7827"
          },
          {
            "name": "AVG New Customers Value: Previous Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "CALCULATE(",
              "[AVG New Customers Value],",
              "DATEADD( 'Dim: Calendar'[date] , -1, YEAR )",
              ")"
            ],
            "lineageTag": "a30102e5-25b2-4404-b099-9e502fe17e45"
          },
          {
            "name": "AVG New Customers Value: vs PY Reference Label",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "VAR yoyChange = [AVG New Customers Value] - [AVG New Customers Value: Previous Year]",
              "VAR changePercentage = DIVIDE( [AVG New Customers Value] - [AVG New Customers Value: Previous Year] , [AVG New Customers Value: Previous Year] , 0 )",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( yoyChange, \"$#,#\" ) & \")\" & \" vs same period last year\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( yoyChange, \"$#,#\" ) & \")\" & \" vs same period last year\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "0b70a16d-94a2-4d3b-8490-c4902138081b"
          },
          {
            "name": "AVG New Customers Value: vs PD Reference Label",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "VAR dodChange = [AVG New Customers Value] - [AVG New Customers Value: Previous Day]",
              "VAR changePercentage = DIVIDE( [AVG New Customers Value] - [AVG New Customers Value: Previous Day] , [AVG New Customers Value: Previous Day] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"▲ \" & FORMAT( changePercentage, \"0%\" ) & \" (\" & FORMAT( dodChange, \"$#,#\" ) & \")\" & \" vs previous day\", ",
              "    changePercentage = 0 , \"—\",",
              "    changePercentage < 0 , \"▼ \" & FORMAT( ABS(changePercentage), \"0%\" ) & \" (\" & FORMAT( dodChange, \"$#,#\" ) & \")\" & \" vs previous day\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "28321bf4-357e-48bd-a64b-619de9f8b3f5"
          },
          {
            "name": "Sales: Dynamic Ranking by Events",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR rankByOrders = ",
              "RANK(",
              "    DENSE,",
              "    ALLSELECTED( 'Dim: Events'[name] ), ",
              "    ORDERBY( [Complete Orders], DESC, 'Dim: Events'[name], ASC )",
              ")",
              "VAR rankByTickets = ",
              "RANK(",
              "    DENSE,",
              "    ALLSELECTED( 'Dim: Events'[name] ), ",
              "    ORDERBY( [Tickets], DESC, 'Dim: Events'[name], ASC )",
              ")",
              "VAR rankByDiscount = ",
              "RANK(",
              "    DENSE,",
              "    ALLSELECTED( 'Dim: Events'[name] ), ",
              "    ORDERBY( [Discount], DESC, 'Dim: Events'[name], ASC )",
              ")",
              "VAR rankByProfit = ",
              "RANK(",
              "    DENSE,",
              "    ALLSELECTED( 'Dim: Events'[name] ), ",
              "    ORDERBY( [Profit], DESC, 'Dim: Events'[name], ASC )",
              ")",
              "VAR whiteSpace = UNICHAR(127)",
              "VAR result =",
              "SWITCH(",
              "    selectedParam,",
              "    1, rankByOrders,",
              "    2, rankByTickets,",
              "    3, rankByDiscount,",
              "    4, rankByProfit",
              ")",
              "RETURN result",
              "// IF( result < 10, ",
              "//     \"# \" & whiteSpace & result,",
              "//     \"# \" & result",
              "// )"
            ],
            "formatString": "0",
            "lineageTag": "10612403-d429-4600-ba17-88425a87334a"
          },
          {
            "name": "Filter: Sales Metrics",
            "displayFolder": "7. Filter",
            "expression": [
              "",
              "INT( ISEVEN( SELECTEDVALUE( 'Param: Summary Metrics'[Order] ) ) )"
            ],
            "formatString": "0",
            "lineageTag": "edff9985-06ba-45e9-b4de-c08352dc0fbb"
          },
          {
            "name": "Events: Status",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR Result = ",
              "IF(",
              "    SELECTEDVALUE( 'Dim: Events'[isOpening] ) = 0,",
              "    UNICHAR(11044) & \" Closed\",",
              "    UNICHAR(11044) & \" Opening\"",
              ")",
              "",
              "RETURN IF( NOT ISBLANK( [Summary: Dynamic] ), Result )"
            ],
            "lineageTag": "8b5673de-e0e7-4700-958a-4ca81d223b82"
          },
          {
            "name": "Filter: Days Period",
            "displayFolder": "7. Filter",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Day Period Slicer'[Order] )",
              "VAR maxDateID = CALCULATE( MAX( 'Fact: Orders'[creationDateID] ), REMOVEFILTERS() )",
              "VAR maxDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], maxDateID )",
              "VAR dateTable = ",
              "SELECTCOLUMNS(",
              "FILTER( ",
              "    'Dim: Calendar',",
              "    'Dim: Calendar'[date] >= maxDate - selectedParam && 'Dim: Calendar'[date] <= maxDate",
              "),",
              "'Dim: Calendar'[date]",
              ")",
              "VAR result = IF( SELECTEDVALUE( 'Dim: Calendar'[date] ) IN SELECTCOLUMNS( dateTable, 'Dim: Calendar'[date] ), 1 , 0 )",
              "RETURN result"
            ],
            "formatString": "0",
            "lineageTag": "4a9adae0-ddd4-49b9-8665-d6cf5546ca76"
          },
          {
            "name": "PYMT: % of Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR totalValue = CALCULATE( [Summary: Dynamic], ALL('Fact: Orders'[paymentMethod]) )",
              "VAR percentageOfTotal = DIVIDE( [Summary: Dynamic], totalValue )",
              "RETURN percentageOfTotal"
            ],
            "lineageTag": "8b593e6b-1733-4349-907f-6dcd4958437b"
          },
          {
            "name": "Dummy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": "0.1",
            "lineageTag": "08606534-331d-485e-a1ac-e044fa675d67"
          },
          {
            "name": "PYMT: Data Label",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR selectedMeasure = SELECTEDVALUE('Param: Summary Metrics Slicer'[Group])",
              "VAR formattedValue = ",
              "IF(",
              "    selectedMeasure IN {3,4},",
              "    SWITCH(",
              "        TRUE(),",
              "        [Summary: Dynamic] < 1000, FORMAT([Summary: Dynamic], \"$0\"),",
              "        [Summary: Dynamic] < 1000000, FORMAT([Summary: Dynamic], \"$#,K\"),",
              "        [Summary: Dynamic] < 1000000000, FORMAT([Summary: Dynamic], \"$#,,.00M\"),",
              "        [Summary: Dynamic] >= 1000000000, FORMAT([Summary: Dynamic], \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( [Summary: Dynamic], \"#,#\" )",
              ")",
              "VAR result = formattedValue & \" | \" & FORMAT( [PYMT: % of Total], \"0%\" )",
              "RETURN result"
            ],
            "lineageTag": "ec6212af-0147-4761-8b37-8837614624c2"
          },
          {
            "name": "Gender: % of Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR totalValue = CALCULATE( [Summary: Dynamic], ALL('Dim: Customers'[gender]) )",
              "VAR percentageOfTotal = DIVIDE( [Summary: Dynamic], totalValue )",
              "RETURN percentageOfTotal"
            ],
            "lineageTag": "6bd2d01a-07f8-46a1-bd2d-223029922ff8"
          },
          {
            "name": "Gender: Data Label",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR selectedMeasure = SELECTEDVALUE('Param: Summary Metrics Slicer'[Group])",
              "VAR formattedValue = ",
              "IF(",
              "    selectedMeasure IN {3,4},",
              "    SWITCH(",
              "        TRUE(),",
              "        [Summary: Dynamic] < 1000, FORMAT([Summary: Dynamic], \"$0\"),",
              "        [Summary: Dynamic] < 1000000, FORMAT([Summary: Dynamic], \"$#,K\"),",
              "        [Summary: Dynamic] < 1000000000, FORMAT([Summary: Dynamic], \"$#,,.00M\"),",
              "        [Summary: Dynamic] >= 1000000000, FORMAT([Summary: Dynamic], \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( [Summary: Dynamic], \"#,#\" )",
              ")",
              "VAR result = REPT( UNICHAR(127), 1 ) & formattedValue & \" | \" & FORMAT( [Gender: % of Total], \"0%\" )",
              "RETURN result"
            ],
            "lineageTag": "c517de0d-e3b0-4cac-b4b1-bcc9a5bdb2c8"
          },
          {
            "name": "Filter: Days Period v2",
            "displayFolder": "7. Filter",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Day Period Slicer'[Order] )",
              "VAR maxDateID = CALCULATE( MAX( 'Fact: Orders'[purchaseDateID] ), REMOVEFILTERS() )",
              "VAR maxDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], maxDateID )",
              "VAR dateTable = ",
              "SELECTCOLUMNS(",
              "FILTER( ",
              "    'Dim: Calendar',",
              "    'Dim: Calendar'[date] >= maxDate - selectedParam && 'Dim: Calendar'[date] <= maxDate",
              "),",
              "'Dim: Calendar'[date]",
              ")",
              "VAR result = IF( selectedParam = 0, 1, IF( SELECTEDVALUE( 'Dim: Calendar'[date] ) IN SELECTCOLUMNS( dateTable, 'Dim: Calendar'[date] ), 1 , 0 ) )",
              "RETURN result"
            ],
            "formatString": "0",
            "lineageTag": "794aade6-f89a-4a27-80ba-a9755f7d52e3"
          },
          {
            "name": "Summary: Dynamic Tooltip",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "9. Tooltip",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, [Orders: vs PD Reference Label],",
              "    2, [Tickets: vs PD Reference Label],",
              "    3, [Discount],",
              "    4, [Profit: vs PD Reference Label]",
              ")",
              "RETURN result"
            ],
            "lineageTag": "194e4392-45c3-4a8a-bfa5-6e4c5dba1ffd"
          },
          {
            "name": "New Customers Value",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] )",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' )",
              ")",
              "",
              "VAR NewCustomers = ",
              "EXCEPT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result = ",
              "SUMX(",
              "    NewCustomers,",
              "    [Profit]",
              ")",
              "",
              "RETURN Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "71f123a8-7f0f-474b-89f7-82e007c46124"
          },
          {
            "name": "Repeat Customers Value",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ) ",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' )",
              ")",
              "",
              "VAR RepeatCustomers = ",
              "INTERSECT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result =",
              "SUMX(",
              "    RepeatCustomers,",
              "    [Profit]",
              ")",
              "",
              "RETURN Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "3a7a4d29-9309-49b8-8f81-15896190e54a"
          },
          {
            "name": "New Customers Tickets",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] )",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' )",
              ")",
              "",
              "VAR NewCustomers = ",
              "EXCEPT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result = ",
              "SUMX(",
              "    NewCustomers,",
              "    [Tickets]",
              ")",
              "",
              "RETURN Result"
            ],
            "formatString": "#,0",
            "lineageTag": "77de0a00-1026-4ad5-b7be-d7af7e6e6778"
          },
          {
            "name": "Repeat Customers Tickets",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ) ",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' )",
              ")",
              "",
              "VAR RepeatCustomers = ",
              "INTERSECT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result =",
              "SUMX(",
              "    RepeatCustomers,",
              "    [Tickets]",
              ")",
              "",
              "RETURN Result"
            ],
            "formatString": "#,0",
            "lineageTag": "6a5dda06-1f17-4d0f-96cd-3e5435467b14"
          },
          {
            "name": "Upper Constant Line",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MaxDate = CALCULATE( MAX( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "VAR MinDate = CALCULATE( MIN( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "",
              "VAR MaxValue =",
              "CALCULATE(",
              "    MAXX(",
              "        ALLSELECTED( 'Dim: Calendar'[date] ),",
              "        [Summary: Dynamic]",
              "    )",
              ")",
              "",
              "VAR Result = IF( SELECTEDVALUE( 'Dim: Calendar'[date] ) = MaxDate || SELECTEDVALUE( 'Dim: Calendar'[date] ) = MinDate, MaxValue * 1.5, BLANK() ) ",
              "",
              "RETURN Result"
            ],
            "lineageTag": "98f4e758-fde9-4456-b5c8-9101c55db79d"
          },
          {
            "name": "Max Date Marker",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MaxDate = CALCULATE( MAX( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "",
              "VAR MaxValue =",
              "CALCULATE(",
              "    MAXX(",
              "        ALLSELECTED( 'Dim: Calendar'[date] ),",
              "        [Summary: Dynamic]",
              "    )",
              ")",
              "",
              "VAR Result = IF( SELECTEDVALUE( 'Dim: Calendar'[date] ) = MaxDate, MaxValue * -0.5, BLANK() ) ",
              "",
              "RETURN Result"
            ],
            "lineageTag": "3ec932af-863e-47fa-9edc-afd9991e0c12"
          },
          {
            "name": "Min Date Marker",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MinDate = CALCULATE( MIN( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "",
              "VAR MaxValue =",
              "CALCULATE(",
              "    MAXX(",
              "        ALLSELECTED( 'Dim: Calendar'[date] ),",
              "        [Summary: Dynamic]",
              "    )",
              ")",
              "",
              "VAR Result = IF( SELECTEDVALUE( 'Dim: Calendar'[date] ) = MinDate, MaxValue * -0.5, BLANK() ) ",
              "",
              "RETURN Result"
            ],
            "lineageTag": "0f72b1aa-3834-4832-b2b9-195f23197310"
          },
          {
            "name": "Min Date Label",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "FORMAT( CALCULATE( MIN( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) ), \"dd/mm/yyyy\")"
            ],
            "lineageTag": "bda40cba-e3a7-414a-95e9-d9065297e2a0"
          },
          {
            "name": "Trend line: Y Scale",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MaxValue =",
              "CALCULATE(",
              "    MAXX(",
              "        ALLSELECTED( 'Dim: Calendar'[date] ),",
              "        [Summary: Dynamic]",
              "    )",
              ")",
              "",
              "RETURN MaxValue * 1.75"
            ],
            "lineageTag": "8e96870f-12d8-4d59-928d-08b32e06cd89"
          },
          {
            "name": "Overall Trend",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MaxDate = CALCULATE( MAX( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "VAR MinDate = CALCULATE( MIN( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "",
              "VAR MaxDateValue = CALCULATE( [Summary: Dynamic], 'Dim: Calendar'[date] = MaxDate )",
              "VAR MinDateValue = CALCULATE( [Summary: Dynamic], 'Dim: Calendar'[date] = MinDate )",
              "VAR Difference = MaxDateValue - MinDateValue",
              "",
              "VAR Trends = DIVIDE( Difference, MinDateValue, 0 )",
              "VAR SelectedMeasure = SELECTEDVALUE('Param: Summary Metrics'[Group])",
              "VAR CallOut = ",
              "IF(",
              "    SelectedMeasure IN {3,4},",
              "    SWITCH(",
              "        TRUE(),",
              "        ABS(Difference) < 1000000, FORMAT( ABS(Difference),  \"$#,#\" ),",
              "        ABS(Difference) < 1000000000, FORMAT( ABS(Difference),  \"$#,,.00M\" ),",
              "        ABS(Difference) >= 1000000000, FORMAT( ABS(Difference), \"$#,,,.00B\" )",
              "    ),",
              "    FORMAT( ABS(Difference), \"#,#\" )",
              ")",
              "",
              "VAR Result = ",
              "SWITCH(",
              "    TRUE(),",
              "    Trends > 0, \"▲ \" & FORMAT( Trends, \"#,#%\" ) & \" | \" & CallOut,",
              "    Trends = 0, \"No Change\",",
              "    Trends < 0, \"▼ \" & FORMAT( ABS(Trends), \"#,#%\" ) & \" | \" & CallOut",
              ")",
              "",
              "RETURN Result"
            ],
            "lineageTag": "dc3bcb22-5ed4-4b1b-ad67-649c1eef307a"
          },
          {
            "name": "Max Date Label",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "FORMAT( CALCULATE( MAX( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) ), \"dd/mm/yyyy\")"
            ],
            "lineageTag": "2dc31f26-ec52-4de5-8e4e-e7c1a695af09"
          },
          {
            "name": "Peak Marker",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        ALLSELECTED( 'Dim: Calendar'[date] ),",
              "        [Summary: Dynamic]",
              "    )",
              ")",
              "",
              "VAR DateOfMaxValueTable = ",
              "CALCULATETABLE(",
              "    VALUES( 'Dim: Calendar'[date]),",
              "    FILTER(",
              "        ALL( 'Dim: Calendar' ),",
              "        [Summary: Dynamic] = MaxValue",
              "    )",
              ")",
              "",
              "VAR DateOfMaxValue = TOPN( 1, DateOfMaxValueTable )",
              "",
              "VAR Result = IF( FORMAT( SELECTEDVALUE( 'Dim: Calendar'[date] ), \"dd/mm/yyyy\" ) = FORMAT( DateOfMaxValue, \"dd/mm/yyyy\" ), MaxValue, BLANK() )",
              "",
              "RETURN Result"
            ],
            "lineageTag": "4c591687-5d87-4d01-9ee8-3e4bd664222b"
          },
          {
            "name": "Low Marker",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MinValue = ",
              "CALCULATE(",
              "    MINX(",
              "        ALLSELECTED( 'Dim: Calendar'[date] ),",
              "        [Summary: Dynamic]",
              "    )",
              ")",
              "",
              "VAR DateOfMinValueTable = ",
              "CALCULATETABLE(",
              "    VALUES( 'Dim: Calendar'[date] ) ,",
              "    FILTER(",
              "        ALL( 'Dim: Calendar' ),",
              "        [Summary: Dynamic] = MinValue",
              "    )",
              ")",
              "",
              "VAR DateOfMinValue =",
              "TOPN( 1, DateOfMinValueTable )",
              "",
              "VAR Result = IF( FORMAT( SELECTEDVALUE( 'Dim: Calendar'[date] ), \"dd/mm/yyyy\" ) = FORMAT( DateOfMinValue, \"dd/mm/yyyy\" ), MinValue, BLANK() )",
              "",
              "RETURN Result"
            ],
            "lineageTag": "15562e99-9beb-44d3-8931-2dfd4fc12f4d"
          },
          {
            "name": "Trend Label Detail",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR measureName = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \" orders\",",
              "    2, \" tickets\",",
              "    3, \" \",",
              "    4, \" \"",
              ")",
              "",
              "RETURN measureName"
            ],
            "lineageTag": "628ae69d-bb64-438a-9378-765fef981ef3"
          },
          {
            "name": "Repeat Customers Discount",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ) ",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' )",
              ")",
              "",
              "VAR RepeatCustomers = ",
              "INTERSECT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result =",
              "SUMX(",
              "    RepeatCustomers,",
              "    [Discount]",
              ")",
              "",
              "RETURN Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1d5fa0bc-9370-4b9b-94e8-88dac305b590"
          },
          {
            "name": "New Customers Discount",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] )",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' )",
              ")",
              "",
              "VAR NewCustomers = ",
              "EXCEPT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result = ",
              "SUMX(",
              "    NewCustomers,",
              "    [Discount]",
              ")",
              "",
              "RETURN Result"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a4421af7-d2c8-4bcb-a447-172f854e64a7"
          },
          {
            "name": "Hierarchical rank",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR RankedByEvents = ",
              "RANK(",
              "    DENSE,",
              "    ALLSELECTED( 'Dim: Events'[name] ),",
              "    ORDERBY( [Summary: Dynamic], DESC, 'Dim: Events'[name], ASC )",
              ")",
              "",
              "VAR RankedByTickets = ",
              "RANK(",
              "    DENSE,",
              "    ALLSELECTED( 'Dim: Tickets'[distance] ),",
              "    ORDERBY( [Summary: Dynamic], DESC, 'Dim: Tickets'[distance], ASC )",
              ")",
              "",
              "VAR Result = ",
              "SWITCH(",
              "    TRUE(),",
              "    ISINSCOPE( 'Dim: Tickets'[distance] ), RankedByTickets,",
              "    ISINSCOPE( 'Dim: Events'[name] ), RankedByEvents",
              ")",
              "",
              "RETURN Result"
            ],
            "formatString": "0",
            "lineageTag": "7de9e6a3-d4f6-4eb3-9921-1e48eccae95b"
          },
          {
            "name": "Trend line: vs PD",
            "displayFolder": "9. Tooltip",
            "expression": [
              "",
              "VAR PDValue =",
              "CALCULATE(",
              "    [Summary: Dynamic],",
              "    DATEADD( 'Dim: Calendar'[date], -1, DAY )",
              ")",
              "",
              "VAR DoDChange = [Summary: Dynamic] - PDValue",
              "VAR ChangePercentage = DIVIDE( DoDChange, PDValue, 0 )",
              "",
              "VAR SelectedMeasure = SELECTEDVALUE('Param: Summary Metrics'[Group])",
              "VAR CallOut =",
              "IF(",
              "    SelectedMeasure IN {3,4},",
              "    SWITCH(",
              "        TRUE(),",
              "        ABS(DoDChange) < 1000000, FORMAT( ABS(DoDChange),  \"$#,#\" ),",
              "        ABS(DoDChange) < 1000000000, FORMAT( ABS(DoDChange),  \"$#,,.00M\" ),",
              "        ABS(DoDChange) >= 1000000000, FORMAT( ABS(DoDChange), \"$#,,,.00B\" )",
              "    ),",
              "    FORMAT( ABS(DoDChange), \"#,#\" )",
              ")",
              "",
              "VAR Result = ",
              "SWITCH(",
              "    TRUE(),",
              "    ChangePercentage > 0, \"▲ \" & FORMAT( ChangePercentage, \"#,#%\" ) & \" (\" & CallOut & \") \",",
              "    ChangePercentage = 0, \"No change\",",
              "    ChangePercentage < 0, \"▼ \" & FORMAT( ABS(ChangePercentage), \"#,#%\" ) & \" (\" & CallOut & \") \"",
              ")",
              "",
              "RETURN Result"
            ],
            "lineageTag": "fdf8edaa-b85d-4def-ad0f-33a0095b1966"
          },
          {
            "name": "AG: Y Scale",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "CALCULATE(",
              "    MAXX( ",
              "        ALLSELECTED( 'Dim: Customers'[ageGroup] ),",
              "        [Summary: Dynamic]",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Customers' )",
              ") * 1.5"
            ],
            "lineageTag": "a687b11a-de6c-4bcb-8d3a-67f947fb8c90"
          },
          {
            "name": "Summary: % of Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR percentageByEvent = ",
              "CALCULATE(",
              "    DIVIDE(",
              "        [Summary: Dynamic],",
              "        CALCULATE( [Summary: Dynamic], ALLSELECTED( 'Dim: Events'[name] ) ),",
              "        0",
              "    )",
              ")",
              "VAR percentageByTicket = ",
              "CALCULATE(",
              "    DIVIDE(",
              "        [Summary: Dynamic],",
              "        CALCULATE( [Summary: Dynamic], ALLSELECTED( 'Dim: Tickets'[distance] ) ),",
              "        0",
              "    )",
              ")",
              "VAR result =",
              "SWITCH(",
              "    TRUE(),",
              "    NOT ISBLANK([Complete Orders]) && ISINSCOPE( 'Dim: Tickets'[distance] ), percentageByTicket,",
              "    NOT ISBLANK([Complete Orders]) && ISINSCOPE( 'Dim: Events'[name] ), percentageByEvent",
              ")",
              "RETURN result"
            ],
            "lineageTag": "bd93e376-13d2-4aac-b175-9974cce8cc47"
          },
          {
            "name": "! Test",
            "displayFolder": "8. Summary",
            "expression": [
              "",
              "VAR MaxDOS = MAX( 'Fact: Orders'[creationDateID] )",
              "VAR MinDOS = MIN( 'Fact: Orders'[creationDateID] )",
              "VAR MaxDOSValue = CALCULATE( [Summary: Dynamic], 'Dim: Calendar'[dateID] = MaxDOS )",
              "VAR MinDOSValue = CALCULATE( [Summary: Dynamic], 'Dim: Calendar'[dateID] = MinDOS )",
              "VAR ChangePercentage = DIVIDE( MaxDOSValue - MinDOSValue, MinDOSValue )",
              "VAR Result =",
              "SWITCH(",
              "    TRUE(),",
              "    ChangePercentage > 0 , \"Trending Up ⇧\",",
              "    ChangePercentage = 0 , \"No Change\",",
              "    ChangePercentage < 0 , \"Trending Down ⇩\"",
              ")",
              "",
              "RETURN Result"
            ],
            "lineageTag": "0a348c2b-510a-4e0e-adaf-cf676444788d"
          },
          {
            "name": "Format Profit",
            "displayFolder": "3. KPI - Profit",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Profit] < 1000000, FORMAT( [Profit],  \"#,.0K\" ),",
              "    [Profit] < 1000000000, FORMAT( [Profit],  \"#,,.00M\" ),",
              "    [Profit] >= 1000000000, FORMAT( [Profit], \"#,,,.00B\" )",
              ")"
            ],
            "lineageTag": "9e3b2491-64c0-4af2-a4b8-b828d1eb1e60"
          },
          {
            "name": "Measure",
            "displayFolder": "4. KPI - Customers",
            "expression": [
              "",
              "RANK(",
              "    DENSE,",
              "    ALLSELECTED( 'Dim: Events'[name] ),",
              "    ORDERBY( [New Customers], DESC, 'Dim: Events'[name], ASC )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1d00acd2-9809-454d-bc6d-fa7a1c09d1ed"
          }
        ],
        "partitions": [
          {
            "name": "2. Summary",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim: Events",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c41476e-04c9-40d2-85f0-796dc9fcb16f",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c9dbac2-06f6-43b3-9774-279082da0c95",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeeec923-2273-48ad-844e-8390674ce700",
            "sourceColumn": "location",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e82974f6-c3e5-43e7-8f9b-168d601b9d9f",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "809a2f77-3a80-461c-b1cf-3bf8c954d743",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "openDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ba06532e-07fa-4a0c-b5b8-9f0eacac2818",
            "sourceColumn": "openDate",
            "summarizeBy": "none"
          },
          {
            "name": "closeDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bb57b9ef-84a3-459b-aa9b-ad1fe8a2226f",
            "sourceColumn": "closeDate",
            "summarizeBy": "none"
          },
          {
            "name": "isOpening",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "INT( 'Dim: Events'[closeDate] > DATE( 2024, 03, 21 ) ) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ff6fcb58-2550-45d5-9bc6-51a2c9bb47ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "statusSlicer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF( 'Dim: Events'[isOpening] = 0, \"Closed\", \"Opening\" )",
            "isDataTypeInferred": true,
            "lineageTag": "d48b41ba-c50a-4c48-9446-0b60549b9383",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "09ede75c-0369-4543-a5eb-296cb574e4b3",
            "sourceColumn": "target",
            "summarizeBy": "none"
          },
          {
            "name": "tickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "[Tickets]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a1febf5b-5d3a-4ece-bc1e-4b73eb7eafa9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "a2d50dfd-fa74-49ea-abc0-7c563bfacb6f",
        "partitions": [
          {
            "name": "Dim: Events",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\dev\\activeTix\\data\\events.csv\"),[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"id\", Int64.Type}, {\"name\", type text}, {\"location\", type text}, {\"type\", type text}, {\"date\", type datetime}, {\"ticket_open_date2\", type datetime}, {\"ticket_close_date\", type datetime}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ticket_open_date2\", \"openDate\"}, {\"ticket_close_date\", \"closeDate\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"target\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim: Tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "960b520b-f5a8-4084-92bc-055d8122f1cd",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "eventID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75eacbab-8124-4e11-98d2-10d30931699b",
            "sourceColumn": "eventID",
            "summarizeBy": "count"
          },
          {
            "name": "distance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02922b1a-b70c-4030-befc-701e0f0b1607",
            "sourceColumn": "distance",
            "summarizeBy": "none"
          },
          {
            "name": "phaseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b31b77e-d5c6-4a1f-9d03-201653b3f53d",
            "sourceColumn": "phaseID",
            "summarizeBy": "none"
          },
          {
            "name": "price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4170d077-b773-4500-a5ec-86f5ffd96289",
            "sourceColumn": "price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "162c73fe-6c1a-4661-8760-5686280eb05f",
        "partitions": [
          {
            "name": "Dim: Tickets",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\dev\\activeTix\\data\\bi\\tickets.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"\", Int64.Type}, {\"ticket_id\", Int64.Type}, {\"event_id\", Int64.Type}, {\"distance\", type text}, {\"phase_id\", Int64.Type}, {\"price\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"ticket_id\", \"id\"}, {\"event_id\", \"eventID\"}, {\"phase_id\", \"phaseID\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim: Customers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f498b6b-32ba-4a79-a84e-11fcfff9d2aa",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "dob",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "41aa4040-718b-472c-8629-e10add283f86",
            "sourceColumn": "dob",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "601877b7-232c-4c4e-8b0b-83c731bf0987",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acf947cb-ddb0-4367-b09d-44f4be330d81",
            "sourceColumn": "state",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb44d169-261c-4975-8835-a04c8e3757cb",
            "sourceColumn": "gender",
            "summarizeBy": "none"
          },
          {
            "name": "creationTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "6108c335-b1c8-48b0-8c1f-bc19a3f3678f",
            "sourceColumn": "creationTime",
            "summarizeBy": "none"
          },
          {
            "name": "lastLoginTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "5c418ef8-a928-4abb-95a7-bf2230155559",
            "sourceColumn": "lastLoginTime",
            "summarizeBy": "none"
          },
          {
            "name": "creationDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9de54bef-45a3-4aa0-8d45-4204cd52f204",
            "sourceColumn": "creationDateID",
            "summarizeBy": "none"
          },
          {
            "name": "lastLoginDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79907a60-27e2-4817-9be3-bcead3876621",
            "sourceColumn": "lastLoginDateID",
            "summarizeBy": "none"
          },
          {
            "name": "age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b113145-cad6-469d-9e6d-8a4094558b05",
            "sourceColumn": "age",
            "summarizeBy": "none"
          },
          {
            "name": "ageGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "245189a1-2fca-454a-b7c2-3d34a3022778",
            "sortByColumn": "ageGroupOrder",
            "sourceColumn": "ageGroup",
            "summarizeBy": "none"
          },
          {
            "name": "ageGroupOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "388c9927-d9f6-4d6c-bf8b-56ff76b9e823",
            "sourceColumn": "ageGroupOrder",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "393f3a81-521e-444c-8472-91cb0e6c4405",
        "partitions": [
          {
            "name": "Dim: Customers",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\dev\\activeTix\\data\\bi\\customers.csv\"),[Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_id\", Int64.Type}, {\"first_name\", type text}, {\"last_name\", type text}, {\"email\", type text}, {\"date_of_birth\", type date}, {\"street_address\", type text}, {\"city\", type text}, {\"state\", type text}, {\"gender\", type text}, {\"created_at\", type datetime}, {\"updated_at\", type datetime}, {\"last_login_at\", type datetime}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"customer_id\", \"date_of_birth\", \"city\", \"state\", \"gender\", \"created_at\", \"last_login_at\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"customer_id\", \"id\"}, {\"date_of_birth\", \"dob\"}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Renamed Columns\", \"Date\", each DateTime.Date([created_at]), type date),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Date\",{{\"Date\", \"creationDate\"}}),",
                "    #\"Inserted Date1\" = Table.AddColumn(#\"Renamed Columns1\", \"Date\", each DateTime.Date([last_login_at]), type date),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Date1\",{{\"Date\", \"lastLoginDate\"}}),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Renamed Columns2\", \"Time\", each DateTime.Time([created_at]), type time),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Inserted Time\",{{\"Time\", \"creationTime\"}}),",
                "    #\"Inserted Time1\" = Table.AddColumn(#\"Renamed Columns3\", \"Time\", each DateTime.Time([last_login_at]), type time),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Inserted Time1\",{{\"Time\", \"lastLoginTime\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns4\",{\"created_at\", \"last_login_at\"}),",
                "    #\"Add creationDateID\" = Table.AddColumn(#\"Removed Columns\", \"creationDateID\", each Date.ToText( [creationDate], [Format=\"yyyyMMdd\"] )),",
                "    #\"Add lastLoginDateID\" = Table.AddColumn(#\"Add creationDateID\", \"lastLoginDateID\", each Date.ToText( [lastLoginDate], [Format=\"yyyyMMdd\"] )),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Add lastLoginDateID\",{{\"creationDateID\", Int64.Type}, {\"lastLoginDateID\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"creationDate\", \"lastLoginDate\"}),",
                "    #\"Inserted Age\" = Table.AddColumn(#\"Removed Columns1\", \"Age\", each Date.From(DateTime.LocalNow()) - [dob], type duration),",
                "    #\"Calculated Total Years\" = Table.TransformColumns(#\"Inserted Age\",{{\"Age\", each Duration.TotalDays(_) / 365, type number}}),",
                "    #\"Rounded Up\" = Table.TransformColumns(#\"Calculated Total Years\",{{\"Age\", Number.RoundUp, Int64.Type}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Rounded Up\", \"ageGroup\", each if [Age] >= 70 then \"70 and Above\" else if [Age] >= 60 then \"60 - 69\" else if [Age] >= 50 then \"50 - 59\" else if [Age] >= 40 then \"40 - 49\" else if [Age] >= 30 then \"30 - 39\" else if [Age] >= 25 then \"25 - 29\" else if [Age] >= 16 then \"16 - 24\" else \"Others\"),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"ageGroupOrder\", each if [ageGroup] = \"16 - 24\" then 1 else if [ageGroup] = \"25 - 29\" then 2 else if [ageGroup] = \"30 - 39\" then 3 else if [ageGroup] = \"40 - 49\" then 4 else if [ageGroup] = \"50 - 59\" then 5 else if [ageGroup] = \"60 - 69\" then 6 else if [ageGroup] = \"70 and Above\" then 7 else 8),",
                "    #\"Renamed Columns5\" = Table.RenameColumns(#\"Added Conditional Column1\",{{\"Age\", \"age\"}})",
                "in",
                "    #\"Renamed Columns5\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact: Orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a28002fd-4931-435e-a1b5-e7e5652ab902",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "customerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c31e66fc-8a2a-40e2-a146-e09b12ce3e4d",
            "sourceColumn": "customerID",
            "summarizeBy": "none"
          },
          {
            "name": "ticketID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a78a84c-02b1-437a-a282-a851c12ec956",
            "sourceColumn": "ticketID",
            "summarizeBy": "none"
          },
          {
            "name": "eventID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "449fb0f3-0960-43c9-ad72-838bbdad796d",
            "sourceColumn": "eventID",
            "summarizeBy": "none"
          },
          {
            "name": "totalTickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9146ee7f-9d6a-47e8-a239-ca62b1670628",
            "sourceColumn": "totalTickets",
            "summarizeBy": "none"
          },
          {
            "name": "discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "429aae3b-c9ac-4b56-a1ab-03618fff5efb",
            "sourceColumn": "discount",
            "summarizeBy": "none"
          },
          {
            "name": "price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4d23f44f-10c8-42ec-8f75-c60722cb1792",
            "sourceColumn": "price",
            "summarizeBy": "none"
          },
          {
            "name": "orderStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "19a00f90-3011-44c6-91ed-4284801086fe",
            "sourceColumn": "orderStatus",
            "summarizeBy": "sum"
          },
          {
            "name": "paymentMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "228a4a2d-7edf-434f-ab68-392f9d92021d",
            "sourceColumn": "paymentMethod",
            "summarizeBy": "none"
          },
          {
            "name": "creationDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41b1ce41-0438-4485-a3e6-cbedbea485f5",
            "sourceColumn": "creationDateID",
            "summarizeBy": "none"
          },
          {
            "name": "creationTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "1ab0458b-db9e-4c1b-bcb5-2e53f9b8020d",
            "sourceColumn": "creationTime",
            "summarizeBy": "none"
          },
          {
            "name": "purchaseDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b37a061b-0253-44b8-bc6d-09b34f081bcb",
            "sourceColumn": "purchaseDateID",
            "summarizeBy": "count"
          },
          {
            "name": "todSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d1eb140-0599-44f4-b918-98a51fd4e5c0",
            "sourceColumn": "todSort",
            "summarizeBy": "sum"
          },
          {
            "name": "checkoutTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27ee08c3-bb18-45f2-934a-1e300161e5a3",
            "sourceColumn": "checkoutTime",
            "summarizeBy": "none"
          },
          {
            "name": "purchaseTOD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ca650c4-a406-469b-8a9d-c471107a2fcb",
            "sortByColumn": "todSort",
            "sourceColumn": "purchaseTOD",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8ede34bc-6ce7-446b-a843-2b5661c91d88",
        "partitions": [
          {
            "name": "Fact: Orders",
            "mode": "import",
            "queryGroup": "Fact tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\dev\\activeTix\\data\\orders.csv\"),[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"order_id\", Int64.Type}, {\"customer_id\", Int64.Type}, {\"ticket_id\", Int64.Type}, {\"event_id\", Int64.Type}, {\"total_tickets\", Int64.Type}, {\"order_status\", type text}, {\"payment_method\", type text}, {\"created_at\", type datetime}, {\"completed_at\", type datetime}, {\"cancelled_at\", type datetime}, {\"price\", Int64.Type}, {\"discount\", type number}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Changed Type\",{\"order_id\", \"customer_id\", \"ticket_id\", \"event_id\", \"total_tickets\", \"discount\", \"price\", \"order_status\", \"payment_method\", \"created_at\", \"completed_at\", \"cancelled_at\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"total_tickets\", \"totalTickets\"}, {\"ticket_id\", \"ticketID\"}, {\"event_id\", \"eventID\"}, {\"order_id\", \"id\"}, {\"order_status\", \"orderStatus\"}, {\"payment_method\", \"paymentMethod\"}, {\"customer_id\", \"customerID\"}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Renamed Columns\",{{\"created_at\", Order.Descending}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Sorted Rows\",\"succeeded\",\"1\",Replacer.ReplaceText,{\"orderStatus\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"failed\",\"0\",Replacer.ReplaceText,{\"orderStatus\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value1\", \"checkoutTime\", each [completed_at] - [created_at]),",
                "    #\"Extracted Minutes\" = Table.TransformColumns(#\"Added Custom\",{{\"checkoutTime\", Duration.Minutes, Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Extracted Minutes\", \"dateID\", each DateTime.ToText( [completed_at], [Format=\"yyyyMMdd\"] )),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"dateID\", Int64.Type}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Changed Type1\",{\"dateID\", \"id\", \"customerID\", \"ticketID\", \"eventID\", \"totalTickets\", \"discount\", \"price\", \"orderStatus\", \"paymentMethod\", \"checkoutTime\", \"created_at\", \"completed_at\", \"cancelled_at\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"dateID\", \"purchaseDateID\"}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Renamed Columns1\", \"creationDateID\", each DateTime.ToText( [created_at], [Format=\"yyyyMMdd\"] )),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"creationDateID\", Int64.Type}}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Changed Type2\",{\"creationDateID\", \"purchaseDateID\", \"id\", \"customerID\", \"ticketID\", \"eventID\", \"totalTickets\", \"discount\", \"price\", \"orderStatus\", \"paymentMethod\", \"checkoutTime\", \"created_at\", \"completed_at\", \"cancelled_at\"}),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Reordered Columns2\", \"Time\", each DateTime.Time([created_at]), type time),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Time\",{{\"Time\", \"creationTime\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns2\",{\"created_at\"}),",
                "    #\"Inserted Time1\" = Table.AddColumn(#\"Removed Columns\", \"Time\", each DateTime.Time([completed_at]), type time),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Inserted Time1\",{{\"Time\", \"purchaseTime\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"completed_at\", \"cancelled_at\"}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Removed Columns1\",{\"creationDateID\", \"creationTime\", \"purchaseDateID\", \"purchaseTime\", \"id\", \"customerID\", \"ticketID\", \"eventID\", \"totalTickets\", \"discount\", \"price\", \"orderStatus\", \"paymentMethod\", \"checkoutTime\"}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Reordered Columns3\", \"Custom\", each Time.ToText( [purchaseTime], [Format=\"hh tt\"])),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Added Custom3\",{{\"Custom\", \"purchaseTOD\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns4\",{{\"purchaseTOD\", type text}}),",
                "    #\"Reordered Columns4\" = Table.ReorderColumns(#\"Changed Type3\",{\"creationDateID\", \"creationTime\", \"purchaseDateID\", \"purchaseTOD\", \"purchaseTime\", \"id\", \"customerID\", \"ticketID\", \"eventID\", \"totalTickets\", \"discount\", \"price\", \"orderStatus\", \"paymentMethod\", \"checkoutTime\"}),",
                "    #\"Extracted Hour\" = Table.TransformColumns(#\"Reordered Columns4\",{{\"purchaseTime\", Time.Hour, Int64.Type}}),",
                "    #\"Renamed Columns5\" = Table.RenameColumns(#\"Extracted Hour\",{{\"purchaseTime\", \"todSort\"}})",
                "in",
                "    #\"Renamed Columns5\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim: Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "453e374b-1ad9-46aa-a402-f6f31441174d",
            "sourceColumn": "dateID",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "000a6064-9aa9-40ad-85b6-80232be21c51",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "dayOfWeekShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "71eebaea-bc8a-49e9-9d56-f55831961ebd",
            "sortByColumn": "dayOfWeekInt",
            "sourceColumn": "dayOfWeekShort",
            "summarizeBy": "none"
          },
          {
            "name": "dayOfWeekLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9997288f-cb8e-4d7f-a3b2-e8080b8a9d0b",
            "sourceColumn": "dayOfWeekLong",
            "summarizeBy": "none"
          },
          {
            "name": "dayOfWeekInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cc48f21-d024-49f2-b1c5-aae86b30dae0",
            "sourceColumn": "dayOfWeekInt",
            "summarizeBy": "none"
          },
          {
            "name": "dayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8573ddf-0fef-43c9-bbc0-35de7e90fddc",
            "sourceColumn": "dayOfMonth",
            "summarizeBy": "none"
          },
          {
            "name": "currDayOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a92918e3-2172-4bcc-b424-d6866c8cf0fb",
            "sourceColumn": "currDayOffset",
            "summarizeBy": "none"
          },
          {
            "name": "monthInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8074155e-135e-4cf0-a9ca-5972f26b0177",
            "sourceColumn": "monthInt",
            "summarizeBy": "none"
          },
          {
            "name": "monthShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2cb1109-d4a3-45f1-8eee-a187ad61b246",
            "sortByColumn": "monthInt",
            "sourceColumn": "monthShort",
            "summarizeBy": "none"
          },
          {
            "name": "monthLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c5f5dda-caee-4293-977d-d679f5bfc332",
            "sourceColumn": "monthLong",
            "summarizeBy": "none"
          },
          {
            "name": "currMonthOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b51b9698-ca5d-4d53-aa45-3dbc0107e73d",
            "sourceColumn": "currMonthOffset",
            "summarizeBy": "none"
          },
          {
            "name": "yearMonthInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71e4cb83-f258-4fb4-b0ea-3a208d9820bd",
            "sourceColumn": "yearMonthInt",
            "summarizeBy": "none"
          },
          {
            "name": "yearMonthShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "40722892-ec38-4241-8ee0-889c89aaf0f9",
            "sortByColumn": "yearMonthInt",
            "sourceColumn": "yearMonthShort",
            "summarizeBy": "none"
          },
          {
            "name": "yearMonthLong",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e0c3674-e4f3-405a-b793-96ded1f6d2d6",
            "sortByColumn": "yearMonthInt",
            "sourceColumn": "yearMonthLong",
            "summarizeBy": "none"
          },
          {
            "name": "quarterInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8903d79-d7ff-4760-91c8-0995bd75f1dc",
            "sourceColumn": "quarterInt",
            "summarizeBy": "none"
          },
          {
            "name": "quarterTxt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7df6c2fb-12af-4e58-93de-8e4e725d7ee5",
            "sourceColumn": "quarterTxt",
            "summarizeBy": "none"
          },
          {
            "name": "currQuarterOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d9ed2a2-e406-4068-9c7a-bc21c4069d42",
            "sourceColumn": "currQuarterOffset",
            "summarizeBy": "none"
          },
          {
            "name": "yearQuarterInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70cd3aa3-e30b-4f57-a071-131343d11bc2",
            "sourceColumn": "yearQuarterInt",
            "summarizeBy": "none"
          },
          {
            "name": "yearQuarterTxt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e39103ae-f4be-4edd-9395-6882a8257aca",
            "sourceColumn": "yearQuarterTxt",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "153a20c5-e80b-4519-9cb5-eac4d4e9ae18",
            "sourceColumn": "year",
            "summarizeBy": "none"
          },
          {
            "name": "currYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c12e3a8-02a2-4c3a-ae80-9224dd33724b",
            "sourceColumn": "currYearOffset",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "3de9cc54-fa79-41b4-b39a-494712dc4219",
        "partitions": [
          {
            "name": "Dim: Calendar",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database(),",
                "    #\"duckdbt-pipeline\" = Source{[Name=\"duckdbt-pipeline\"]}[Data],",
                "    techhaus_Schema = #\"duckdbt-pipeline\"{[Name=\"techhaus\",Kind=\"Schema\"]}[Data],",
                "    calendar_View = techhaus_Schema{[Name=\"calendar\",Kind=\"View\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(calendar_View,{{\"date_id\", \"dateID\"}, {\"current_day_offset\", \"currDayOffset\"}, {\"current_month_offset\", \"currMonthOffset\"}, {\"current_quarter_offset\", \"currQuarterOffset\"}, {\"current_year_offset\", \"currYearOffset\"}, {\"day_of_month\", \"dayOfMonth\"}, {\"day_of_week_int\", \"dayOfWeekInt\"}, {\"day_of_week_long\", \"dayOfWeekLong\"}, {\"day_of_week_short\", \"dayOfWeekShort\"}, {\"month_int\", \"monthInt\"}, {\"month_long\", \"monthLong\"}, {\"month_short\", \"monthShort\"}, {\"quarter_int\", \"quarterInt\"}, {\"quarter_txt\", \"quarterTxt\"}, {\"year_month_int\", \"yearMonthInt\"}, {\"year_month_long\", \"yearMonthLong\"}, {\"year_month_short\", \"yearMonthShort\"}, {\"year_quarter_txt\", \"yearQuarterTxt\"}, {\"year_quarter_int\", \"yearQuarterInt\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "5. Color",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "99fa7c40-efc1-4a7e-8d4a-eb7c7a176d71",
        "measures": [
          {
            "name": "Profit: vs PD Reference Label Color",
            "displayFolder": "1.3. Summary: Profit KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Profit] - [Profit: Previous Day] , [Profit: Previous Day] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "7996b32e-2c3b-404d-bc09-df54c3254048"
          },
          {
            "name": "Profit: vs PY Reference Label Color",
            "displayFolder": "1.3. Summary: Profit KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Profit] - [Profit: Previous Year] , [Profit: Previous Year] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "0573cb23-9097-44c6-8ebe-b7088892775d"
          },
          {
            "name": "Tickets: vs PD Reference Label Color",
            "displayFolder": "1.2. Tickets KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Tickets] - [Tickets: Previous Day] , [Tickets: Previous Day] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "a01de812-90d8-4b0f-8001-63416afd6de1"
          },
          {
            "name": "Tickets: vs PY Reference Label Color",
            "displayFolder": "1.2. Tickets KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Tickets] - [Tickets: Previous Year] , [Tickets: Previous Year] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "0d6a1bbe-3bc9-4eaa-b023-b7dc9160b58d"
          },
          {
            "name": "Orders: vs PD Reference Label Color",
            "displayFolder": "1.1. Summary: Orders KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Complete Orders] - [Orders: Previous Day] , [Orders: Previous Day] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "72226e54-36f3-459f-b1f1-566cf477ffe8"
          },
          {
            "name": "Orders: vs PY Reference Label Color",
            "displayFolder": "1.1. Summary: Orders KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Complete Orders] - [Orders: Previous Year] , [Orders: Previous Year] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "73e05e5a-c870-4130-8d49-03a76df6e21a"
          },
          {
            "name": "Active Customers: vs PD Reference Label Color",
            "displayFolder": "1.4. Summary: Customers KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [New Customers] - [New Customers: Previous Day] , [New Customers: Previous Day] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "d25bc5e4-4a58-460d-a139-b6530498cf4c"
          },
          {
            "name": "Active Customers: vs PY Reference Label Color",
            "displayFolder": "1.4. Summary: Customers KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [New Customers] - [New Customers: Previous Year] , [New Customers: Previous Year] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "08dea838-3e2d-431a-9eec-1335cdf078c0"
          },
          {
            "name": "Profit Margin: vs PD Reference Label Color",
            "displayFolder": "1.3. Summary: Profit KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Profit Margin] - [Profit Margin: Previous Day] , [Profit Margin: Previous Day] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "9b282739-d050-49aa-8667-e483f5a5f0d3"
          },
          {
            "name": "Profit Margin: vs PY Reference Label Color",
            "displayFolder": "1.3. Summary: Profit KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [Profit Margin] - [Profit Margin: Previous Year] , [Profit Margin: Previous Year] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "a73d5729-ee3e-40f7-8301-0c1f10bdd522"
          },
          {
            "name": "AVG Tickets per Order: vs PD Reference Label Color",
            "displayFolder": "1.2. Tickets KPI",
            "expression": [
              "",
              "\t\t\tVAR changePercentage = DIVIDE( [AVG Tickets per Order] - [AVG Tickets per Order: Previous Day] , [AVG Tickets per Order: Previous Day] , 0 )",
              "\t\t\tVAR result = ",
              "\t\t\tSWITCH( ",
              "\t\t\t\tTRUE(),",
              "\t\t\t\tchangePercentage > 0 , \"#2589BD\", ",
              "\t\t\t\tchangePercentage = 0 , \"midColor\",",
              "\t\t\t\tchangePercentage < 0 , \"#8C2C35\"",
              "\t\t\t)",
              "\t\t\tRETURN result"
            ],
            "lineageTag": "0a366d13-9a58-44b4-b3c6-e1629a199fd4"
          },
          {
            "name": "AVG Tickets per Order: vs PY Reference Label Color",
            "displayFolder": "1.2. Tickets KPI",
            "expression": [
              "",
              "\t\t\tVAR changePercentage = DIVIDE( [AVG Tickets per Order] - [AVG Tickets per Order: Previous Year] , [AVG Tickets per Order: Previous Year] , 0 )",
              "\t\t\tVAR result = ",
              "\t\t\tSWITCH( ",
              "\t\t\t\tTRUE(),",
              "\t\t\t\tchangePercentage > 0 , \"#2589BD\", ",
              "\t\t\t\tchangePercentage = 0 , \"midColor\",",
              "\t\t\t\tchangePercentage < 0 , \"#8C2C35\"",
              "\t\t\t)",
              "\t\t\tRETURN result"
            ],
            "lineageTag": "3b529130-fa83-46e5-acdf-bdb32eebf806"
          },
          {
            "name": "Completion %: vs PD Reference Label Color",
            "displayFolder": "1.1. Summary: Orders KPI",
            "expression": [
              "",
              "\tVAR changePercentage = DIVIDE( [Completion Rate] - [Completion %: Previous Day] , [Completion %: Previous Day] , 0 )",
              "\tVAR result = ",
              "\tSWITCH( ",
              "\t\tTRUE(),",
              "\t\tchangePercentage > 0 , \"#2589BD\", ",
              "\t\tchangePercentage = 0 , \"midColor\",",
              "\t\tchangePercentage < 0 , \"#8C2C35\"",
              "\t)",
              "\tRETURN result"
            ],
            "lineageTag": "e0a23390-f34e-4265-b7bc-75a3f4aec77b"
          },
          {
            "name": "Completion %: vs PY Reference Label Color",
            "displayFolder": "1.1. Summary: Orders KPI",
            "expression": [
              "",
              "\tVAR changePercentage = DIVIDE( [Completion Rate] - [Completion %: Previous Year] , [Completion %: Previous Year] , 0 )",
              "\tVAR result = ",
              "\tSWITCH( ",
              "\t\tTRUE(),",
              "\t\tchangePercentage > 0 , \"#2589BD\", ",
              "\t\tchangePercentage = 0 , \"midColor\",",
              "\t\tchangePercentage < 0 , \"#8C2C35\"",
              "\t)",
              "\tRETURN result"
            ],
            "lineageTag": "89d35c34-6092-4353-a670-69b35375b13d"
          },
          {
            "name": "AVG New Customers Value: vs PD Reference Label Color",
            "displayFolder": "1.4. Summary: Customers KPI",
            "expression": [
              "",
              "VAR changePercentage = DIVIDE( [AVG New Customers Value] - [AVG New Customers Value: Previous Day] , [AVG New Customers Value: Previous Day] , 0 )",
              "VAR result = ",
              "SWITCH( ",
              "    TRUE(),",
              "    changePercentage > 0 , \"#2589BD\", ",
              "    changePercentage = 0 , \"midColor\",",
              "    changePercentage < 0 , \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "200302c4-c894-4055-932e-ef2b876797f8"
          },
          {
            "name": "AVG New Customers Value: vs PY Reference Label Color",
            "displayFolder": "1.4. Summary: Customers KPI",
            "expression": [
              "",
              "\tVAR changePercentage = DIVIDE( [AVG New Customers Value] - [AVG New Customers Value: Previous Year] , [AVG New Customers Value: Previous Year] , 0 )",
              "\tVAR result = ",
              "\tSWITCH( ",
              "\t\tTRUE(),",
              "\t\tchangePercentage > 0 , \"#2589BD\", ",
              "\t\tchangePercentage = 0 , \"midColor\",",
              "\t\tchangePercentage < 0 , \"#8C2C35\"",
              "\t)",
              "\tRETURN result"
            ],
            "lineageTag": "9855fe9e-bb52-4f79-9c3c-1913ba692ebd"
          },
          {
            "name": "Summary: Events Status Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "IF( ",
              "    SELECTEDVALUE( 'Dim: Events'[isOpening] ) = 0, ",
              "    \"#8C2C35\",",
              "    \"#2589BD\"",
              ")"
            ],
            "lineageTag": "35541380-14a4-4491-8ef0-ae11590eaa9a"
          },
          {
            "name": "Summary: by AG - Bar Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "IF( ",
              "    [Summary: Dynamic] = ",
              "    CALCULATE(",
              "        MAXX( ",
              "            ALL( 'Dim: Customers'[ageGroup] ),",
              "            [Summary: Dynamic]",
              "        ),",
              "    REMOVEFILTERS('Dim: Customers')",
              "    ),",
              "    \"#2589BD\"",
              "    ,",
              "    \"#CCCCCC\"",
              ")"
            ],
            "lineageTag": "73d331e4-2163-4648-a1e1-1b351f03a8d2"
          },
          {
            "name": "Summary: Rank by PYMT Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "IF( ",
              "    [Summary: Dynamic] = ",
              "    CALCULATE(",
              "        MAXX( ",
              "            ALL( 'Fact: Orders'[paymentMethod] ),",
              "            [Summary: Dynamic]",
              "        ),",
              "    REMOVEFILTERS('Dim: Customers')",
              "    ),",
              "    \"#5C5C5C\"",
              "    ,",
              "    \"#CCCCCC\"",
              ")"
            ],
            "lineageTag": "1395cc14-245e-412d-98d9-83de308ef3a9"
          },
          {
            "name": "Sales: MoM Change % Text Color",
            "displayFolder": "2.1. Sales: MoM Matrix",
            "expression": [
              "",
              "VAR PM = CALCULATE( [Sales: Dynamic], PREVIOUSMONTH( 'Dim: Calendar'[date] ) )",
              "VAR MoMChange = [Sales: Dynamic] - PM",
              "VAR ChangePctg = DIVIDE( MoMChange, PM, 0 )",
              "VAR result = ",
              "SWITCH(",
              "    TRUE(),",
              "    MoMChange > 0, \"#2589BD\",",
              "    MoMChange = 0, \"midColor\",",
              "    MoMChange < 0, \"#8C2C35\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "a47a87d0-1561-4f12-8e75-b8dc4ddb98ca"
          },
          {
            "name": "Sales: Profit Margin Color",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Profit Margin] >= 0.8, \"#2589BD\",",
              "    [Profit Margin] >= 0.6, \"#F3D2B5\",",
              "    [Profit Margin] < 0.6, \"#8C2C35\"",
              ")"
            ],
            "lineageTag": "ee90ef92-b277-4590-9dba-f927d2acea3e"
          },
          {
            "name": "Sales: Profit vs AVG Color",
            "expression": [
              "",
              "IF( ROUND([AVG profit per Order],0) >= ROUND([Sales: Average Order Value of Selected Events],0), \"#2589BD\", \"#8C2C35\" )"
            ],
            "lineageTag": "c63d04bc-42b3-401a-a44d-0f833d7db348"
          },
          {
            "name": "Sales: Scatter Plot Dynamic Color",
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Scatter Cluster Color'[Order] ),",
              "    0, \"#2589BD\",",
              "    1, [Sales: Profit Margin Color],",
              "    2, [Sales: Profit vs AVG Color]",
              ")"
            ],
            "lineageTag": "a1839b13-cf8b-4861-b49c-516a3ee021cf"
          },
          {
            "name": "Sales: Scatter Plot Legends",
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Scatter Legends'[segmentID]),",
              "    0, \"#2589BD\",",
              "    1, \"#2589BD\",",
              "    2, \"#F3D2B5\",",
              "    3, \"#8C2C35\",",
              "    4, \"#2589BD\",",
              "    5, \"#8C2C35\"",
              ")"
            ],
            "lineageTag": "941564b7-4ea9-4276-a900-d2c204975197"
          },
          {
            "name": "Sales: Scatter Plot Tooltip Value Color",
            "expression": [
              "",
              "VAR avgOrderValue = IF( ROUND([AVG profit per Order],0) >= ROUND(CALCULATE( [Sales: Average Order Value of Selected Events], REMOVEFILTERS( 'Dim: Events') ), 0), \"#2589BD\", \"#8C2C35\" )",
              "VAR result =",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Scatter Cluster Color'[Order] ),",
              "    0, \"#2589BD\",",
              "    1, [Sales: Profit Margin Color],",
              "    2, avgOrderValue",
              ")",
              "RETURN result"
            ],
            "lineageTag": "148fbf32-763c-4a33-855a-515f2a73bc37"
          },
          {
            "name": "Sales: Cluster Bar Chart Tooltip Reference 1 Color",
            "expression": [
              "",
              "// Daily View",
              "VAR PD = ",
              "    CALCULATE(",
              "    [Sales: Dynamic],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              "    )",
              "VAR dodChange = [Sales: Dynamic] - PD",
              "VAR dodChangePerc = DIVIDE( DoDChange, PD, 0 )",
              "VAR dodDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    dodChangePerc > 0, \"#2589BD\",",
              "    dodChangePerc = 0, \"midColor\",",
              "    dodChangePerc < 0, \"#8C2C35\"",
              ")",
              "",
              "// Monthly View",
              "VAR PM = ",
              "    CALCULATE(",
              "    [Sales: Dynamic],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, MONTH ) ",
              "    )",
              "",
              "VAR momChange = [Sales: Dynamic] - PM",
              "VAR momChangePerc = DIVIDE( momChange, PM, 0 )",
              "VAR momDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    momChangePerc > 0, \"#2589BD\",",
              "    momChangePerc = 0, \"midColor\",",
              "    momChangePerc < 0, \"#8C2C35\"",
              ")",
              "",
              "// Choose which measure to display",
              "VAR result = IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), dodDisplay, momDisplay )",
              "RETURN result"
            ],
            "lineageTag": "6b434b6a-02e6-4441-92b0-7e7fa5e13546"
          },
          {
            "name": "Sales: Cluster Bar Chart Tooltip Reference 2 Color",
            "expression": [
              "",
              "// Daily View",
              "VAR dodChange = [Sales: Dynamic] - [Sales: Dynamic SPLY]",
              "VAR dodChangePerc = DIVIDE( DoDChange, [Sales: Dynamic SPLY], 0 )",
              "VAR dodDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    dodChangePerc > 0, \"#2589BD\",",
              "    dodChangePerc = 0, \"midColor\",",
              "    dodChangePerc < 0, \"#8C2C35\"",
              ")",
              "",
              "// Monthly View",
              "VAR momChange = [Sales: Dynamic] - [Sales: Dynamic SPLY]",
              "VAR momChangePerc = DIVIDE( momChange, [Sales: Dynamic SPLY], 0 )",
              "VAR momDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    momChangePerc > 0, \"#2589BD\",",
              "    momChangePerc = 0, \"midColor\",",
              "    momChangePerc < 0, \"#8C2C35\"",
              ")",
              "",
              "// Choose which measure to display",
              "VAR result = IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), dodDisplay, momDisplay )",
              "RETURN result"
            ],
            "lineageTag": "31cc8403-dcea-4a18-b8d5-a11744af71d3"
          },
          {
            "name": "Transparent",
            "expression": "\"#FFFFFF00\" ",
            "lineageTag": "22cd8531-cd19-44e4-9d3d-18f5ac849f97"
          },
          {
            "name": "Summary: Overall Trend Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "VAR MaxDate = CALCULATE( MAX( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "VAR MinDate = CALCULATE( MIN( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) )",
              "",
              "VAR MaxDateValue = CALCULATE( [Summary: Dynamic], 'Dim: Calendar'[date] = MaxDate )",
              "VAR MinDateValue = CALCULATE( [Summary: Dynamic], 'Dim: Calendar'[date] = MinDate )",
              "",
              "VAR Trends = DIVIDE( MaxDateValue - MinDateValue, MinDateValue, 0 )",
              "VAR Result = ",
              "SWITCH(",
              "    TRUE(),",
              "    Trends > 0, \"#2589BD\",",
              "    Trends = 0, \"#333333\",",
              "    Trends < 0, \"#8C2C35\"",
              ")",
              "",
              "RETURN IF( FORMAT( SELECTEDVALUE( 'Dim: Calendar'[date]), \"dd/mm/yyyy\" ) = FORMAT( MaxDate, \"dd/mm/yyyy\" ), Result, \"#FFFFFF00\" )"
            ],
            "lineageTag": "78b458ed-05e8-4ded-9bf5-d0e93e013a1f"
          },
          {
            "name": "Summary: Max Date Label Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "VAR MaxDate = FORMAT( CALCULATE( MAX( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) ), \"dd/mm/yyyy\")",
              "VAR Result = IF( FORMAT( SELECTEDVALUE( 'Dim: Calendar'[date] ), \"dd/mm/yyyy\" ) = MaxDate, \"#333333\", \"#FFFFFF00\" )",
              "RETURN Result"
            ],
            "lineageTag": "8beb505d-190b-4d89-834c-b13f10c903ca"
          },
          {
            "name": "Summary: Min Date Label Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "VAR MaxDate = FORMAT( CALCULATE( MIN( 'Dim: Calendar'[date] ), ALLSELECTED( 'Dim: Calendar'[date] ) ), \"dd/mm/yyyy\")",
              "VAR Result = IF( FORMAT( SELECTEDVALUE( 'Dim: Calendar'[date] ), \"dd/mm/yyyy\" ) = MaxDate, \"#333333\", \"#FFFFFF00\" )",
              "RETURN Result"
            ],
            "lineageTag": "4364758f-be3e-4087-ab7b-4532445505ff"
          },
          {
            "name": "Sales: MoM Change % BG Color",
            "displayFolder": "2.1. Sales: MoM Matrix",
            "expression": [
              "",
              "VAR PM = CALCULATE( [Sales: Dynamic], PREVIOUSMONTH( 'Dim: Calendar'[date] ) )",
              "VAR MoMChange = [Sales: Dynamic] - PM",
              "VAR ChangePctg = DIVIDE( MoMChange, PM, 0 )",
              "VAR result = ",
              "SWITCH(",
              "    TRUE(),",
              "    MoMChange > 0, \"#d3e7f1\",",
              "    MoMChange = 0, \"#F6F6F6\",",
              "    MoMChange < 0, \"#e8d4d6\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "3c29b81a-b348-41a4-8518-9523c12de3f6"
          },
          {
            "name": "Summary: Trend line tooltip",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(),",
              "    CONTAINSSTRING( [Trend line: vs PD], \"▲\" ), \"#2589BD\", ",
              "    CONTAINSSTRING( [Trend line: vs PD], \"No Change\" ), \"#5C5C5C\",",
              "    CONTAINSSTRING( [Trend line: vs PD], \"▼\" ), \"#8C2C35\"",
              ")"
            ],
            "lineageTag": "925880bb-e9d6-42d6-a7b5-89c841e8dc52"
          },
          {
            "name": "Summary: by AG - Text Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "IF( ",
              "    [Summary: Dynamic] = ",
              "    CALCULATE(",
              "        MAXX( ",
              "            ALL( 'Dim: Customers'[ageGroup] ),",
              "            [Summary: Dynamic]",
              "        ),",
              "    REMOVEFILTERS('Dim: Customers')",
              "    ),",
              "    \"#2589BD\"",
              "    ,",
              "    \"#ADADAD\"",
              ")"
            ],
            "lineageTag": "857deceb-7b13-4c10-91cb-43cad4647109"
          },
          {
            "name": "Summary: Repeat Customer Text Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers] < [Repeat Customers], \"#2589BD\", ",
              "    [New Customers] = [Repeat Customers], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")"
            ],
            "lineageTag": "e3347baf-c9d1-470b-aa75-79deef2a8866"
          },
          {
            "name": "Summary: New Customer Text Color",
            "displayFolder": "1.5. Summary: Others",
            "expression": [
              "",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers] > [Repeat Customers], \"#2589BD\", ",
              "    [New Customers] = [Repeat Customers], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")"
            ],
            "lineageTag": "cdec80e5-04c6-4d5a-8f38-6849ad29754e"
          }
        ],
        "partitions": [
          {
            "name": "5. Color",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Param: Summary Metrics",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "549edca717d14a178034d06d7bbc2ddd"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "95141072-e53d-4bb2-a6e4-750760461b80",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Field"
                }
              ]
            },
            "sortByColumn": "Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4befd366-e851-4813-a503-7ad4bd8bb80d",
            "sortByColumn": "Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "67af673d-f06b-47b7-9b47-0a827a8fe1d9",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "86991786-f3e6-4339-aaed-9fad67771334",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "27b13697-3ca8-4c59-bb7f-63322ab9ba66",
        "partitions": [
          {
            "name": "Param: Summary Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Orders\", NAMEOF('1. Core Measures'[Total Orders]), 2, 1),",
                "    (\"Completed\", NAMEOF('1. Core Measures'[Complete Orders]), 3, 1),",
                "    (\"Completion %\", NAMEOF('1. Core Measures'[Completion Rate]), 4, 1),",
                "",
                "    (\"Total Tickets\", NAMEOF('1. Core Measures'[Tickets]), 5, 2),",
                "    (\"Avg / Order\", NAMEOF('1. Core Measures'[AVG Tickets per Order]), 6, 2),",
                "    (\"Avg Profit / Ticket\", NAMEOF('1. Core Measures'[AVG Tickets Value]), 7, 2),",
                "",
                "    (\"Total Discount\", NAMEOF('1. Core Measures'[Discount]), 8, 3),",
                "    (\"Avg % / Order\", NAMEOF('1. Core Measures'[Discount: AVG % per Order]), 9, 3),",
                "    (\"Avg  Value / Order\", NAMEOF('1. Core Measures'[AVG Discount Value]), 10, 3),",
                "    ",
                "    (\"Total Profit\", NAMEOF('1. Core Measures'[Profit]), 11, 4),",
                "    (\"Margin %\", NAMEOF('1. Core Measures'[Profit Margin]), 12, 4),",
                "    (\"Avg / Order\", NAMEOF('1. Core Measures'[AVG profit per Order]), 13, 4)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Param: Summary Metrics Slicer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "52be15f3-693b-4e7e-b0a5-6cf9cc5ddf10",
            "sortByColumn": "Group",
            "sourceColumn": "Measure",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad77381d-7938-40d3-b9ec-287e9fbd94b6",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "eff97636-155e-46ce-8120-9716a298f1de",
        "partitions": [
          {
            "name": "Param: Summary Metrics Slicer",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8i9KSS0qVtJRMlSK1YlWCslMzk4tKVYIzs9JAQoagQVdMouT80vzShTcM8tS84DCxmDhgKL8tMwSINdEKTYWAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measure = _t, Group = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Measure\", type text}, {\"Group\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "6. SVG Image",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "d3138686-6e29-4bd6-925c-4145c290bd31",
        "measures": [
          {
            "name": "Bullet Chart",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR MAXActual = CALCULATE( [Tickets], REMOVEFILTERS( 'Dim: Calendar' ) )",
              "VAR MAXTarget = SELECTEDVALUE( 'Dim: Events'[target] )",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*118",
              "VAR PERCENTAGETARGET = MAXTarget/AXISRANGE*118",
              "RETURN",
              "IF(",
              "    HASONEVALUE('Dim: Events'[name]) && NOT ISBLANK([Summary: Dynamic]) ,",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='120' height='26' viewBox='-2 -2 122 22' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='track' x='0' y='2' width='120' height='24' fill='#E6E6E6' opacity='0'/>",
              "        <rect id='fill' x='0' y='2' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='16' fill='#5C5C5C'></rect>",
              "        <rect id='marker' x=\"&\"'\"&PERCENTAGETARGET&\"'\"&\" y='0' width='4' height='20' fill='#2589BD'></rect>",
              "    </svg>",
              "\", BLANK()",
              ")"
            ],
            "lineageTag": "6b07bddd-f140-4286-83a8-5c949d6f7136"
          },
          {
            "name": "Sparkline",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR lineColor = \"#333333\"",
              "VAR xMinDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MIN( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR xMaxDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR yMinValue = MINX( ALLSELECTED( 'Dim: Calendar'[date] ), CALCULATE( [Summary: Dynamic] ) )",
              "VAR yMaxValue = MINX( ALLSELECTED( 'Dim: Calendar'[date] ), CALCULATE( [Summary: Dynamic] ) )",
              "VAR sparklineTable = ",
              "ADDCOLUMNS(",
              "    SUMMARIZE( \t\t\t",
              "        FILTER(",
              "            'Dim: Calendar',",
              "            'Dim: Calendar'[dateID] IN VALUES('Fact: Orders'[purchaseDateID])",
              "\t\t\t),",
              "\t\t'Dim: Calendar'[date] ",
              "    ),",
              "    \"X\", INT( 120 * DIVIDE( 'Dim: Calendar'[date]  - xMinDate, xMaxDate - xMinDate ) ),",
              "    \"Y\", INT( 40 * DIVIDE( [Summary: Dynamic] - yMinValue, yMaxValue - yMinValue ) )",
              ")",
              "VAR lines = CONCATENATEX( sparklineTable, [X] & \",\" & 40 - [Y], \" \", 'Dim: Calendar'[date] )",
              "VAR image = ",
              "\"data:image/svg+xml;utf8,\" & ",
              "--- gradient---",
              "\"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" &",
              "--- Lines---",
              "\"<polyline ",
              "    fill='transparent' stroke='\" & lineColor & \"' ",
              "    stroke-linecap='round' stroke-linejoin='round' ",
              "    stroke-width='2' points=' \" & lines & ",
              "    \" '/>\" &",
              "\"</svg>\"",
              "RETURN image"
            ],
            "lineageTag": "f33d4fd1-be61-4d88-b3f6-956216f0c133"
          },
          {
            "name": "Donuts: Y % of Total by Events",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR height = 25",
              "VAR width = 150",
              "VAR radius = (height/2) - 2.5",
              "VAR circ = 2*PI()* radius",
              "VAR val = FORMAT( [Sales: Y % of Total by Events], \"#%;-#%;0%\")",
              "VAR a1 =  IF( [Sales: Y % of Total by Events] >= 0,([Sales: Y % of Total by Events] *circ),0)",
              "VAR a2 = (1-[Sales: Y % of Total by Events]) *circ  ",
              "VAR offset = 0.25*circ",
              "VAR sort  = IF([Sales: Y % of Total by Events] <0, 1000+ABS([Sales: Y % of Total by Events]),  10000+ [Sales: Y % of Total by Events])",
              "RETURN",
              "IF(NOT(ISBLANK([Sales: Y % of Total by Events])) && ( ISINSCOPE('Dim: Tickets'[distance]) || ISINSCOPE('Dim: Events'[name]) ), ",
              "\"data:image/svg+xml;utf8,  ",
              "<svg  xmlns='http://www.w3.org/2000/svg' viewBox='0 0 \" & width & \" \" & height & \"'   >",
              " /*\" & sort & \"*/ ",
              "<rect width='150' height='25' style='fill:rgba(0,0,255,0);stroke-width:2;stroke:'/>",
              "<circle class='background' cx='\" & radius + 8 & \"' cy='50%' r='\" & radius & \"' fill='transparent' stroke='#dde1e3' stroke-width='5'   />",
              "<circle class='segment' cx='\" & radius + 8 & \"' cy='50%' r='\" & radius & \"' fill='transparent' stroke='#2589BD' stroke-width='5' stroke-dasharray='\" & a1 & \" \" & a2 & \"' stroke-dashoffset='\" & offset & \"'></circle>",
              "<style>",
              "    .percent {",
              "         font: normal 16pt Segoe UI;",
              "    }",
              "  </style>",
              "<text  x='\" & radius*8 & \"' y='55%' class='percent' text-anchor='end' fill='#666666' alignment-baseline='middle'  >\" & val &\"</text>",
              "</svg>\"",
              ")"
            ],
            "lineageTag": "e8bc2d07-9397-48cd-a63b-8c0a13dc7ad9"
          },
          {
            "name": "Donuts: X % of Total by Events",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR height = 25",
              "VAR width = 150",
              "VAR radius = (height/2) - 2.5",
              "VAR circ = 2*PI()* radius",
              "VAR val = FORMAT( [Sales: X % of Total by Events], \"#%;-#%;0%\")",
              "VAR a1 =  IF( [Sales: X % of Total by Events] >= 0,([Sales: X % of Total by Events] *circ),0)",
              "VAR a2 = (1-[Sales: X % of Total by Events]) *circ  ",
              "VAR offset = 0.25*circ",
              "VAR sort  = IF([Sales: X % of Total by Events] <0, 1000+ABS([Sales: X % of Total by Events]),  10000+ [Sales: X % of Total by Events])",
              "RETURN",
              "IF(NOT(ISBLANK([Sales: X % of Total by Events])) && ( ISINSCOPE('Dim: Tickets'[distance]) || ISINSCOPE('Dim: Events'[name]) ), ",
              "\"data:image/svg+xml;utf8,  ",
              "<svg  xmlns='http://www.w3.org/2000/svg' viewBox='0 0 \" & width & \" \" & height & \"'   >",
              " /*\" & sort & \"*/ ",
              "<rect width='150' height='25' style='fill:rgba(0,0,255,0);stroke-width:2;stroke:'/>",
              "<circle class='background' cx='\" & radius + 8 & \"' cy='50%' r='\" & radius & \"' fill='transparent' stroke='#dde1e3' stroke-width='5'   />",
              "<circle class='segment' cx='\" & radius + 8 & \"' cy='50%' r='\" & radius & \"' fill='transparent' stroke='#2589BD' stroke-width='5' stroke-dasharray='\" & a1 & \" \" & a2 & \"' stroke-dashoffset='\" & offset & \"'></circle>",
              "<style>",
              "    .percent {",
              "         font: normal 16pt Segoe UI;",
              "    }",
              "  </style>",
              "<text  x='\" & radius*8 & \"' y='55%' class='percent' text-anchor='end' fill='#666666' alignment-baseline='middle'  >\" & val &\"</text>",
              "</svg>\"",
              ")"
            ],
            "lineageTag": "ad0b7aab-d750-4cfe-9cba-b5aa323d4105"
          },
          {
            "name": "Bar: Repeat Customers",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR MAXActual = [Repeat Customers]",
              "VAR MAXTarget = [Total Customers]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers] < [Repeat Customers], \"#2589BD\", ",
              "    [New Customers] = [Repeat Customers], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "b6716497-60aa-435a-80e3-735eea742e48"
          },
          {
            "name": "Bar: New Customers",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR MAXActual = [New Customers]",
              "VAR MAXTarget = [Total Customers]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers] > [Repeat Customers], \"#2589BD\", ",
              "    [New Customers] = [Repeat Customers], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "eaea0b57-4678-4905-b257-bdde24df2e7f"
          },
          {
            "name": "Bar: New Customers Value",
            "expression": [
              "",
              "VAR MAXActual = [New Customers Value]",
              "VAR MAXTarget = [Profit]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers Value] > [Repeat Customers Value], \"#2589BD\", ",
              "    [New Customers Value] = [Repeat Customers Value], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "ea5358f8-68eb-4971-b70c-f98b4a873661"
          },
          {
            "name": "Bar: Repeat Customers Value",
            "expression": [
              "",
              "VAR MAXActual = [Repeat Customers Value]",
              "VAR MAXTarget = [Profit]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers Value] < [Repeat Customers Value], \"#2589BD\", ",
              "    [New Customers Value] = [Repeat Customers Value], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "03a44843-9eee-4871-8310-ff97dfdd2801"
          },
          {
            "name": "Bar: New Customers Tickets",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR MAXActual = [New Customers Tickets]",
              "VAR MAXTarget = [Tickets]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers Tickets] > [Repeat Customers Tickets], \"#2589BD\", ",
              "    [New Customers Tickets] = [Repeat Customers Tickets], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "baf99e19-b5fe-4fe6-a4fd-2bbd1efec79f"
          },
          {
            "name": "Bar: Repeat Customers Tickets",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR MAXActual = [Repeat Customers Tickets]",
              "VAR MAXTarget = [Tickets]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers Tickets] < [Repeat Customers Tickets], \"#2589BD\", ",
              "    [New Customers Tickets] = [Repeat Customers Tickets], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "0a9b6497-6f71-4636-a2a0-ea346cabaf9a"
          },
          {
            "name": "Bar: Repeat Customers Discount",
            "expression": [
              "",
              "VAR MAXActual = [Repeat Customers Discount]",
              "VAR MAXTarget = [Discount]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers Discount] < [Repeat Customers Discount], \"#2589BD\", ",
              "    [New Customers Discount] = [Repeat Customers Discount], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "d826c8c3-71c4-43ef-993f-d814a1a415fd"
          },
          {
            "name": "Bar: New Customers Discount",
            "expression": [
              "",
              "VAR MAXActual = [New Customers Discount]",
              "VAR MAXTarget = [Discount]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [New Customers Discount] > [Repeat Customers Discount], \"#2589BD\", ",
              "    [New Customers Discount] = [Repeat Customers Discount], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "178ba811-256b-49ac-971a-0bec7073d032"
          },
          {
            "name": "Bar: Female Customers",
            "expression": [
              "",
              "VAR MAXActual = [Summary: by Female Customers]",
              "VAR MAXTarget = [Summary: Dynamic]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [Summary: by Female Customers] > [Summary: by Male Customers], \"#2589BD\", ",
              "    [Summary: by Female Customers] = [Summary: by Male Customers], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "1e449e5e-adf5-45d5-b2a1-51c3442469dd"
          },
          {
            "name": "Bar: Male Customers",
            "expression": [
              "",
              "VAR MAXActual = [Summary: by Male Customers]",
              "VAR MAXTarget = [Summary: Dynamic]",
              "VAR AXISRANGE = MAXX(",
              "    {",
              "        MAXActual,",
              "        MAXTarget",
              "    },",
              "    [Value]",
              ")",
              "VAR PERCENTAGEFILL = MAXActual/AXISRANGE*326",
              "",
              "VAR FillColor = ",
              "SWITCH( ",
              "    TRUE(),",
              "    [Summary: by Female Customers] < [Summary: by Male Customers], \"#2589BD\", ",
              "    [Summary: by Female Customers] = [Summary: by Male Customers], \"#5C5C5C\",",
              "    \"#8C2C35\"",
              ")",
              "RETURN",
              "\"data:image/svg+xml;utf8,\" & \"",
              "    <svg width='328' height='26' viewBox='0 0 328 12' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' overflow='visible'>",
              "        <rect id='fill' x='0' y='0' rx='4' width='328' height='8' fill='#E6E6E6' ></rect>",
              "        <rect id='fill' x='0' y='0' rx='4' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='8' fill='\"&FillColor&\"' ></rect>",
              "    </svg>",
              "\""
            ],
            "lineageTag": "6bdb9e99-0c98-4e90-822a-b8c204a7955a"
          },
          {
            "name": "Donuts: Summary % of Total",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR Height = 26",
              "VAR Width = 128",
              "VAR Radius = (height/2) - 2.5",
              "VAR Circle = 2*PI()* radius",
              "VAR Callout = FORMAT( [Summary: % of Total], \"0.0%;-0.0%\")",
              "VAR Filled =  IF( [Summary: % of Total] >= 0,([Summary: % of Total] *Circle),0)",
              "VAR Grey = (1-[Summary: % of Total]) * Circle  ",
              "VAR Offset = 0.25*Circle",
              "VAR Sort  = IF([Summary: % of Total] <0, 1000+ABS([Summary: % of Total]),  10000+ [Summary: % of Total])",
              "RETURN",
              "IF(NOT(ISBLANK([Summary: % of Total])) && ( ISINSCOPE('Dim: Tickets'[distance]) || ISINSCOPE('Dim: Events'[name]) ), ",
              "\"data:image/svg+xml;utf8,  ",
              "<svg  xmlns='http://www.w3.org/2000/svg' viewBox='0 0 \" & Width & \" \" & Height & \"'   >",
              " /*\" & Sort & \"*/ ",
              "<rect width='120' height='26' style='fill:rgba(0,0,255,0);stroke-width:2;stroke:'/>",
              "<circle class='background' cx='\" & Radius + 20 & \"' cy='50%' r='\" & Radius & \"' fill='transparent' stroke='#dde1e3' stroke-width='5'   />",
              "<circle class='segment' cx='\" & Radius + 20 & \"' cy='50%' r='\" & Radius & \"' fill='transparent' stroke='#2589BD' stroke-width='5' stroke-dasharray='\" & Filled & \" \" & Grey & \"' stroke-dashoffset='\" & offset & \"'></circle>",
              "<style>",
              "    .percent {",
              "         font: normal 16pt Segoe UI;",
              "    }",
              "  </style>",
              "<text  x='\" & Radius*10 + 16 & \"' y='60%' class='percent' text-anchor='end' fill='#666666' alignment-baseline='middle'  >\" & Callout &\"</text>",
              "</svg>\"",
              ")"
            ],
            "lineageTag": "54bbe187-be34-450f-a544-2eadea5e12ef"
          }
        ],
        "partitions": [
          {
            "name": "6. SVG Image",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Param: Day Period Slicer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7a4ea8ae-4dda-4342-83b1-5f4e4be9c816",
            "sortByColumn": "Order",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bf0495ea-fbb0-42aa-b2e5-2e98e3fedc16",
            "sourceColumn": "Order",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "f4c498a1-f958-4e38-920c-473f495e9e67",
        "partitions": [
          {
            "name": "Param: Day Period Slicer",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlZISawsVtJRMlaK1YlWModxzcFcQxMY39AELGBsAFdvABYwgwuYAQViAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, Order = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Period\", type text}, {\"Order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "7. Title & Subtitle",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "4697f9c0-ff12-4947-85d1-34e0dd33104d",
        "measures": [
          {
            "name": "by Events",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "VAR minDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MIN( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR maxDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR dateDisplay = IF( minDate = maxDate, FORMAT( maxDate, \"dd MMM yyyy\"), \"Between \" & FORMAT( minDate, \"dd MMM yyyy\") & \" and \" & FORMAT( maxDate, \"dd MMM yyyy\") )",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR measureName = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Number of orders completed\",",
              "    2, \"Number of tickets sold\",",
              "    3, \"Amount of discount given\",",
              "    4, \"Amount of profit\"",
              ")",
              "RETURN ",
              "DISTINCTCOUNT( 'Fact: Orders'[eventID] ) ",
              "& \" events with sales | \" ",
              "& \"Total \" ",
              "&",
              "SWITCH(",
              "    SelectedParam,",
              "    1, \"orders completed: \",",
              "    2, \"tickets sold: \",",
              "    3, \"discount given: \",",
              "    4, \"profit: \"",
              ")",
              "&",
              "IF(",
              "    SelectedParam IN {3,4},",
              "    SWITCH(",
              "        TRUE(),",
              "        ABS([Summary: Dynamic]) < 1000000, FORMAT( [Summary: Dynamic],  \"$#,#\" ),",
              "        [Summary: Dynamic] < 1000000000, FORMAT( [Summary: Dynamic],  \"$#,,.00M\" ),",
              "        [Summary: Dynamic] >= 1000000000, FORMAT( [Summary: Dynamic], \"$#,,,.00B\" )",
              "    ),",
              "    FORMAT( [Summary: Dynamic], \"#,#\" )",
              ")",
              "",
              "// \"Current view: \" & measureName & \" | \" & dateDisplay"
            ],
            "lineageTag": "ef1c9102-075a-485c-9e22-d5ea75bbee6c"
          },
          {
            "name": "by Demographics",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "VAR minDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MIN( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR maxDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR dateDisplay = IF( minDate = maxDate, FORMAT( maxDate, \"dd MMM yyyy\"), \"Between \" & FORMAT( minDate, \"dd MMM yyyy\") & \" and \" & FORMAT( maxDate, \"dd MMM yyyy\") )",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR measureName = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Broken down by total orders completed\",",
              "    2, \"Broken down by total tickets purchased\",",
              "    3, \"Broken down by total amount of discount received\",",
              "    4, \"Broken down by total spending\"",
              ")",
              "RETURN measureName & \" | \" & dateDisplay"
            ],
            "lineageTag": "c7199b5c-2450-4172-9dbb-5bc71db43789"
          },
          {
            "name": "by PYMT",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "VAR minDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MIN( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR maxDate = LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[purchaseDateID] ) )",
              "VAR dateDisplay = IF( minDate = maxDate, FORMAT( maxDate, \"dd MMM yyyy\"), \"Between \" & FORMAT( minDate, \"dd MMM yyyy\") & \" and \" & FORMAT( maxDate, \"dd MMM yyyy\") )",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR measureName = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Ranked by total number of orders\",",
              "    2, \"Ranked by total number of tickets\",",
              "    3, \"Ranked by total discount\",",
              "    4, \"Ranked by total profit\"",
              ")",
              "RETURN measureName & \" | \" & dateDisplay"
            ],
            "lineageTag": "252f1c16-8f1c-45e5-ae7d-b84e33e4dc83"
          },
          {
            "name": "Heatmap: Title",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Sales metrics slicer'[order] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Order Completion Volume by Day of the Week and Time\",",
              "    2, \"Ticket Sales Volume by Day of the Week and Time\",",
              "    3, \"Gross Sales Revenue by Day of the Week and Time\",",
              "    4, \"Discount Given by Day of the Week and Time\",",
              "    5, \"Sales Profit by Day of the Week and Time\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "79b67c56-2006-469f-aaf2-896e1d357181"
          },
          {
            "name": "Heatmap: Subtitle",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Sales metrics slicer'[order] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Color scale: BOLDER colors represent HIGHER volume of orders completed\",",
              "    2, \"Color scale: BOLDER colors represent HIGHER volume of tickets\",",
              "    3, \"Color scale: BOLDER colors represent HIGHER amount of revenue\",",
              "    4, \"Color scale: BOLDER colors represent HIGHER amount of discount\",",
              "    5, \"Color scale: BOLDER colors represent HIGHER profit\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "9f1c1644-e7f4-4758-9509-405689e4799a"
          },
          {
            "name": "Bar Chart: Monthly - Title",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Sales metrics slicer'[order] )",
              "VAR CY = SELECTEDVALUE( 'Dim: Calendar'[year] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Monthly Order Completion Trend of the year \" & CY,",
              "    2, \"Monthly Ticket Sales Trend of the year \" & CY,",
              "    3, \"Monthly Gross Sales Trend of the year \" & CY,",
              "    4, \"Monthly Discount Trend of the year \" & CY,",
              "    5, \"Monthly Sales Profit Trend of the year \" & CY",
              ")",
              "RETURN result"
            ],
            "lineageTag": "2ae3f3fc-8282-4c70-a221-36330c30a4c2"
          },
          {
            "name": "Bar Chart: Monthly - Subtitle",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "\"Currently viewing moving average of \" & SELECTEDVALUE( 'Param: Monthly moving average'[period] )"
            ],
            "lineageTag": "7a8699f5-ade4-4cea-8b96-9e2c2588e7c8"
          },
          {
            "name": "Bar Chart: Daily - Title",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Sales metrics slicer'[order] )",
              "VAR CYM = SELECTEDVALUE( 'Dim: Calendar'[monthLong] ) & \" \" & SELECTEDVALUE( 'Dim: Calendar'[year] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Daily Order Completion Trend of \" & CYM,",
              "    2, \"Daily Ticket Sales Trend of \" & CYM,",
              "    3, \"Daily Gross Sales Trend of \" & CYM,",
              "    4, \"Daily Discount Trend of \" & CYM,",
              "    5, \"Daily Sales Profit Trend of \" & CYM",
              ")",
              "RETURN result"
            ],
            "lineageTag": "c0e11ad4-272d-4915-85e1-f98f8ce66c7d"
          },
          {
            "name": "Bar Chart: Daily - Subtitle",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "\"Currently viewing moving average of \" & SELECTEDVALUE( 'Param: Daily moving average'[period] )"
            ],
            "lineageTag": "afdecca5-22d0-4ad2-b84f-13dd332ddf00"
          },
          {
            "name": "Matrix: Title",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Sales metrics slicer'[order] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Month over Month Comparison of Order Completion Volume\",",
              "    2, \"Month over Month Comparison of Ticket Sales Volume\",",
              "    3, \"Month over Month Comparison of Gross Sales Revenue\",",
              "    4, \"Month over Month Comparison of Discount\",",
              "    5, \"Month over Month Comparison of Profit\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "c7a1dff9-52c2-4948-a16d-ca04d058bd02"
          },
          {
            "name": "Summary: Dynamic Title",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Orders Completed\",",
              "    2, \"Tickets Sold\",",
              "    3, \"Discount Given\",",
              "    4, \"Profit\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "bf369d65-3c8d-41d3-a5d3-887bd6360798"
          },
          {
            "name": "Detailed Data Table: Subtitle",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "IF( DISTINCTCOUNT( 'Dim: Calendar'[yearMonthLong] ) = 1,",
              "    DISTINCTCOUNT( 'Fact: Orders'[eventID] ) & \" events have sales in \" & SELECTEDVALUE( 'Dim: Calendar'[monthLong] ) & \" \" & SELECTEDVALUE( 'Dim: Calendar'[year] ),",
              "    DISTINCTCOUNT( 'Fact: Orders'[eventID] ) & \" events have sales in the selected months\"",
              ")"
            ],
            "lineageTag": "5b6d7db2-2cc8-40ca-af5d-a0e9872b3302"
          },
          {
            "name": "Tooltip: Trend line title",
            "expression": [
              "",
              "IF(",
              "    HASONEFILTER( 'Dim: Events'[name] ),",
              "    SELECTEDVALUE( 'Dim: Events'[name] ),",
              "    DISTINCTCOUNT( 'Fact: Orders'[eventID] ) & \" events with sales\"",
              ")"
            ],
            "lineageTag": "b0880771-4699-42bc-aa6b-c1c9b431cffa"
          },
          {
            "name": "Tooltip: Trend line label",
            "expression": [
              "",
              "VAR SelectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR Result =",
              "SWITCH(",
              "    SelectedParam,",
              "    1, \"Orders Completed\",",
              "    2, \"Tickets Sold\",",
              "    3, \"Discount Given\",",
              "    4, \"Profit\"",
              ")",
              "RETURN Result"
            ],
            "lineageTag": "b267c9ec-9bea-41c6-b777-bcc822276f45"
          },
          {
            "name": "Tooltip: Trend line subtitle",
            "expression": [
              "",
              "\"Date: \" & FORMAT( SELECTEDVALUE( 'Dim: Calendar'[date] ), \"dd/mm/yyyy\" )"
            ],
            "lineageTag": "a40bf7f4-2ba2-420b-95f4-e89971f6d514"
          },
          {
            "name": "Tooltip: Trend line details",
            "expression": [
              "",
              "\"vs previous day\""
            ],
            "lineageTag": "f3b1a6bd-f512-4268-ac71-f277a6ec0e76"
          },
          {
            "name": "by Customer types",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER( 'Dim: Tickets'[distance] ), \" \" & SELECTEDVALUE( 'Dim: Events'[name] ) & \" | Distance: \" & SELECTEDVALUE('Dim: Tickets'[distance]),",
              "    HASONEFILTER( 'Dim: Events'[name] ), \" \" & SELECTEDVALUE( 'Dim: Events'[name] ),",
              "    HASONEFILTER( 'Dim: Customers'[ageGroup] ), \"Age Group: \" & SELECTEDVALUE( 'Dim: Customers'[ageGroup] ),",
              "    FORMAT( [Total Customers], \"#,#\" ) & \" customers purchased \" & FORMAT( [Tickets], \"#,#\" ) & \" tickets from \" & DISTINCTCOUNT( 'Fact: Orders'[eventID] ) & \" events\"",
              ")"
            ],
            "lineageTag": "6b188cb0-0cb2-479c-a7e7-d7b905c7e1de"
          },
          {
            "name": "by Male",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "\"among \" &",
              "FORMAT(",
              "    COUNTROWS(",
              "        CALCULATETABLE(",
              "            VALUES( 'Fact: Orders'[customerID] ),",
              "            'Fact: Orders'[orderStatus] = 1,",
              "            'Dim: Customers'[gender] = \"Male\"",
              "        )",
              "    ),",
              "    \"#,#\"",
              ") &",
              "\" Males\""
            ],
            "lineageTag": "cb295ba7-f2ba-40c2-bb80-2936d8464ebc"
          },
          {
            "name": "by Female",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "\"among \" &",
              "FORMAT(",
              "    COUNTROWS(",
              "        CALCULATETABLE(",
              "            VALUES( 'Fact: Orders'[customerID] ),",
              "            'Fact: Orders'[orderStatus] = 1,",
              "            'Dim: Customers'[gender] = \"Female\"",
              "        )",
              "    ),",
              "    \"#,#\"",
              ") &",
              "\" Females\""
            ],
            "lineageTag": "ce06555f-9dcd-4ebd-90cf-679562c53e4d"
          },
          {
            "name": "by Gender",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "VAR SelectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR Result =",
              "SWITCH(",
              "    SelectedParam,",
              "    1, \"Total orders completed\",",
              "    2, \"Total tickets\",",
              "    3, \"Total discount\",",
              "    4, \"Total spending\"",
              ")",
              "RETURN Result"
            ],
            "lineageTag": "e340bfe3-8779-4636-97e4-6f9d7e684110"
          },
          {
            "name": "Summary: Tickets KPI Title",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "REPT( UNICHAR( 127 ), 3 ) & \"Tickets sold\""
            ],
            "lineageTag": "b5f50173-671c-4fd4-9a9f-5c4146d6bff2"
          },
          {
            "name": "Summary: Profit KPI Title",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "REPT( UNICHAR( 127 ), 2 ) & \"Profit ( AUD $ )\""
            ],
            "lineageTag": "343c62ee-1f3e-42be-b4ef-2943bdb6a8b2"
          },
          {
            "name": "Tooltip: Age Group Title",
            "displayFolder": "1. Summary",
            "expression": [
              "",
              "\"Age group: \" & SELECTEDVALUE( 'Dim: Customers'[ageGroup] )"
            ],
            "lineageTag": "eee887ad-9aef-48c3-85e7-8af35d794d6a"
          },
          {
            "name": "Sales: Event Performance Header Text",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "IF( DISTINCTCOUNT( 'Dim: Calendar'[yearMonthLong] ) > 1,",
              "    DISTINCTCOUNT( 'Dim: Calendar'[yearMonthLong] )",
              "    & \" Months selected: \"",
              "    &",
              "    CONCATENATEX( ",
              "        TOPN(",
              "            2,",
              "            SUMMARIZE( FILTER( 'Dim: Calendar', 'Dim: Calendar'[dateID] IN VALUES( 'Fact: Orders'[creationDateID] ) ), 'Dim: Calendar'[yearMonthLong], 'Dim: Calendar'[yearMonthInt] ),",
              "            'Dim: Calendar'[yearMonthInt], DESC",
              "        ),",
              "        'Dim: Calendar'[yearMonthLong],",
              "        \", \",",
              "        'Dim: Calendar'[yearMonthInt],",
              "        DESC",
              "    )",
              "    & \", ...\",",
              "    \"1 Month selected: \" & SELECTEDVALUE( 'Dim: Calendar'[yearMonthLong] )",
              ")"
            ],
            "lineageTag": "789745f3-b7fb-465e-9526-6843b27ba9c3"
          },
          {
            "name": "Sales: Scatter Plot Title",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "VAR selectedX = SELECTEDVALUE( 'Param: Scatter X'[Order] )",
              "VAR xLabel = ",
              "SWITCH(",
              "    selectedX,",
              "    0, \"Number of Tickets\",",
              "    1, \"Amount of Revenue\",",
              "    2, \"Amount of Discount\",",
              "    3, \"Amount of Profit\"",
              ")",
              "",
              "VAR selectedY = SELECTEDVALUE( 'Param: Scatter Y'[Order] )",
              "VAR yLabel = ",
              "SWITCH(",
              "    selectedY,",
              "    0, \"Number of Tickets\",",
              "    1, \"Amount of Revenue\",",
              "    2, \"Amount of Discount\",",
              "    3, \"Amount of Profit\"",
              ")",
              "",
              "",
              "VAR Result = \"Correlation between \" & yLabel & \" and \" & xLabel",
              "RETURN Result"
            ],
            "lineageTag": "8a406309-66d4-46a1-9236-3312dbaf13b0"
          },
          {
            "name": "Sales: Scatter Plot Subtitle",
            "displayFolder": "2. Sales",
            "expression": [
              "",
              "VAR selectedX = SELECTEDVALUE( 'Param: Scatter X'[Order] )",
              "VAR xLabel = ",
              "SWITCH(",
              "    selectedX,",
              "    0, \"X: Tickets\",",
              "    1, \"X: Revenue\",",
              "    2, \"X: Discount\",",
              "    3, \"X: Profit\"",
              ")",
              "",
              "VAR selectedY = SELECTEDVALUE( 'Param: Scatter Y'[Order] )",
              "VAR yLabel = ",
              "SWITCH(",
              "    selectedY,",
              "    0, \"Y: Tickets\",",
              "    1, \"Y: Revenue\",",
              "    2, \"Y: Discount\",",
              "    3, \"Y: Profit\"",
              ")",
              "",
              "VAR Size = SELECTEDVALUE( 'Param: Scatter size'[Order] )",
              "VAR SizeLabel = ",
              "SWITCH(",
              "    selectedY,",
              "    0, \"Size: Tickets\",",
              "    1, \"Size: Revenue\",",
              "    2, \"Size: Discount\",",
              "    3, \"Size: Profit\"",
              ")",
              "",
              "VAR ClusterColor = SELECTEDVALUE( 'Param: Scatter Cluster Color'[Order] )",
              "VAR ClusterColorLabel = ",
              "SWITCH(",
              "    ClusterColor,",
              "    0, \"Cluster Color: Default\",",
              "    1, \"Cluster Color: Profit Margin\",",
              "    2, \"Cluster Color: AVG Order Value\"",
              ")",
              "",
              "VAR Result = yLabel & \" | \" & xLabel & \" | \" & SizeLabel & \" | \" & ClusterColorLabel",
              "RETURN Result"
            ],
            "lineageTag": "be588e21-3849-43ac-8278-3274a3e375bc"
          }
        ],
        "partitions": [
          {
            "name": "7. Title & Subtitle",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "3. Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "7c0213c3-f4e9-4a5f-b7d8-b3d6e1870c45",
        "measures": [
          {
            "name": "Sales: Dynamic SPLY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "1. Core measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales: Dynamic],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, YEAR )",
              ")"
            ],
            "lineageTag": "3b5f70bf-54c5-4fdf-91b4-2f7a2a565597"
          },
          {
            "name": "Positive Upper",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. Cluster bar charts",
            "expression": [
              "",
              "VAR YoYDiff = IF( [Sales: Dynamic] = 0, 0, [Sales: Dynamic] - [Sales: Dynamic SPLY] )",
              "RETURN IF( YoYDiff > 0, [Sales: Dynamic], [Sales: Dynamic SPLY] )"
            ],
            "lineageTag": "c61f00a1-ede0-4d9e-a846-612413291563"
          },
          {
            "name": "Negative Upper",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. Cluster bar charts",
            "expression": [
              "",
              "VAR YoYDiff = IF( [Sales: Dynamic] = 0, 0, [Sales: Dynamic] - [Sales: Dynamic SPLY] )",
              "RETURN IF( YoYDiff < 0, [Sales: Dynamic SPLY], [Sales: Dynamic] )"
            ],
            "lineageTag": "a0456e0c-d516-41e8-9f70-8c93b9642434"
          },
          {
            "name": "Sales: Cluster Bar Chart Visible Dates",
            "displayFolder": "6. Filter",
            "expression": [
              "",
              "IF( SELECTEDVALUE('Dim: Calendar'[dateID]) IN ALL('Fact: Orders'[creationDateID]), 1, 0)"
            ],
            "formatString": "0",
            "lineageTag": "932d22cb-fa13-463b-8f8e-e17d3578d997"
          },
          {
            "name": "Moving AVG by Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. Cluster bar charts",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Daily moving average'[order] )",
              "VAR result =",
              "IF(",
              "    INT( MAX( 'Dim: Calendar'[dateID] ) > MAX( 'Fact: Orders'[creationDateID] ) ) = 1,",
              "    BLANK(),",
              "    CALCULATE(",
              "        AVERAGEX(",
              "            SUMMARIZE( 'Dim: Calendar', 'Dim: Calendar'[date] ),",
              "            [Sales: Dynamic]",
              "        ),",
              "        DATESINPERIOD(",
              "            'Dim: Calendar'[date],",
              "            LASTDATE( 'Dim: Calendar'[date] ),",
              "            selectedParam * -1,",
              "            DAY",
              "        )",
              "    )",
              ")",
              "RETURN result"
            ],
            "lineageTag": "413d646a-2dc3-4738-a63e-eaf3e0bbe941"
          },
          {
            "name": "Sales: MoM Change %",
            "displayFolder": "3. Month over month matrix",
            "expression": [
              "",
              "VAR PM = CALCULATE( [Sales: Dynamic], PREVIOUSMONTH( 'Dim: Calendar'[date] ) )",
              "VAR MoMChange = [Sales: Dynamic] - PM",
              "VAR ChangePctg = DIVIDE( MoMChange, PM, 0 )",
              "VAR whiteSpace = REPT(UNICHAR(127),2)",
              "VAR result = ",
              "SWITCH(",
              "    TRUE(),",
              "    MoMChange > 0, whiteSpace & \"▲ \" & FORMAT( ChangePctg, \"0%\" ),",
              "    MoMChange = 0, whiteSpace & \"—\",",
              "    MoMChange < 0, whiteSpace & \"▼ \" & FORMAT( ABS(ChangePctg), \"0%\" )",
              ")",
              "RETURN result"
            ],
            "lineageTag": "6c1b7f6d-c7f0-4185-9a31-615bee4ed7da"
          },
          {
            "name": "Sales: QTD",
            "displayFolder": "3. Month over month matrix",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALQTD( ",
              "        [Sales: Dynamic],",
              "        'Dim: Calendar'[date]",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _SelectedMeasure = SELECTEDVALUE('Param: Sales metrics slicer'[order])",
                "VAR _CurrentMeasure = SELECTEDMEASURE()",
                "VAR _Format = ",
                "IF(",
                "    _SelectedMeasure IN {3,4,5},",
                "    SWITCH(",
                "        TRUE(),",
                "        _CurrentMeasure < 1000, \"$0\",",
                "        _CurrentMeasure < 1000000, \"$#,#\",",
                "        _CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        _CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN _Format"
              ]
            },
            "lineageTag": "fdab4892-a359-4b98-8e9e-2bfde8e98b3b"
          },
          {
            "name": "Daily view: maxY extended",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. Cluster bar charts",
            "expression": [
              "",
              "VAR maxY = IF( [Sales: Dynamic] = 0, [Sales: Dynamic SPLY], IF( [Sales: Dynamic] > [Sales: Dynamic SPLY], [Sales: Dynamic], [Sales: Dynamic SPLY] ) )",
              "VAR result = ",
              "CALCULATE(",
              "    MAXX(",
              "        VALUES( 'Dim: Calendar'[date] ),",
              "        maxY",
              "    ),",
              "    ALLEXCEPT( 'Dim: Calendar', 'Dim: Calendar'[yearMonthLong] )",
              ") * 0.125",
              "RETURN result"
            ],
            "lineageTag": "4c107db1-b237-4710-a7f3-ce7e0278f7f8"
          },
          {
            "name": "Sales: Daily view - max second Y Extend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. Cluster bar charts",
            "expression": [
              "",
              "VAR maxY =",
              "    CALCULATE(",
              "        MAXX( ",
              "            VALUES( 'Dim: Calendar'[date] ),",
              "            [Moving AVG by Day]",
              "        ),",
              "    ALLEXCEPT( 'Dim: Calendar', 'Dim: Calendar'[yearMonthLong] )",
              "    )",
              "VAR result = maxY * 1.125",
              "RETURN result"
            ],
            "lineageTag": "0a0bba8c-8522-486f-943e-49af0f9a2cad"
          },
          {
            "name": "Sales: YTD",
            "displayFolder": "3. Month over month matrix",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALYTD( ",
              "        [Sales: Dynamic],",
              "        'Dim: Calendar'[date]",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _SelectedMeasure = SELECTEDVALUE('Param: Sales metrics slicer'[order])",
                "VAR _CurrentMeasure = SELECTEDMEASURE()",
                "VAR _Format = ",
                "IF(",
                "    _SelectedMeasure IN {3,4,5},",
                "    SWITCH(",
                "        TRUE(),",
                "        _CurrentMeasure < 1000, \"$0\",",
                "        _CurrentMeasure < 1000000, \"$#,#\",",
                "        _CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        _CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN _Format"
              ]
            },
            "lineageTag": "19508d2e-ccb3-4de2-9950-026adc9c3cbd"
          },
          {
            "name": "Sales: Dynamic",
            "displayFolder": "1. Core measures",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Sales metrics slicer'[order] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, [Complete Orders],",
              "    2, [Tickets],",
              "    3, [Revenue],",
              "    4, [Discount],",
              "    5, [Profit]",
              ")",
              "RETURN result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _SelectedMeasure = SELECTEDVALUE('Param: Sales metrics slicer'[order])",
                "VAR _CurrentMeasure = SELECTEDMEASURE()",
                "VAR _Format = ",
                "IF(",
                "    _SelectedMeasure IN {3,4,5},",
                "    SWITCH(",
                "        TRUE(),",
                "        _CurrentMeasure < 1000, \"$0\",",
                "        _CurrentMeasure < 1000000, \"$#,#\",",
                "        _CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        _CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN _Format"
              ]
            },
            "lineageTag": "ad1fc3f6-ea84-428f-97da-23d2ca754a10"
          },
          {
            "name": "Moving AVG by Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2. Cluster bar charts",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Monthly moving average'[order] )",
              "VAR result =",
              "IF(",
              "    INT( MAX( 'Dim: Calendar'[monthInt] ) > LOOKUPVALUE( 'Dim: Calendar'[monthInt], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[creationDateID] ) ) ) = 1,",
              "    BLANK(),",
              "    CALCULATE(",
              "        AVERAGEX(",
              "            SUMMARIZE( 'Dim: Calendar', 'Dim: Calendar'[monthShort] ),",
              "            [Sales: Dynamic]",
              "        ),",
              "        DATESINPERIOD(",
              "            'Dim: Calendar'[date],",
              "            LASTDATE( 'Dim: Calendar'[date] ),",
              "            selectedParam * -1,",
              "            MONTH",
              "        )",
              "    )",
              ")",
              "RETURN result"
            ],
            "lineageTag": "4e8f17b1-07e9-490d-8e5c-29df2885f286"
          },
          {
            "name": "Sales: Tooltip Y axis scale",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR selectedX = SELECTEDVALUE( 'Param: Scatter X'[Order] )",
              "VAR xMeasure = ",
              "SWITCH(",
              "    selectedX,",
              "    0, [Tickets],",
              "    1, [Revenue],",
              "    2, [Discount],",
              "    3, [Profit]",
              ")",
              "VAR selectedY = SELECTEDVALUE( 'Param: Scatter Y'[Order] )",
              "VAR yMeasure = ",
              "SWITCH(",
              "    selectedY,",
              "    0, [Tickets],",
              "    1, [Revenue],",
              "    2, [Discount],",
              "    3, [Profit]",
              ")",
              "VAR maxY = IF( xMeasure > yMeasure, xMeasure, yMeasure )",
              "VAR result = ",
              "MAXX(",
              "    VALUES( 'Dim: Calendar'[date] ),",
              "    maxY",
              ") * 0.125",
              "RETURN result"
            ],
            "formatString": "0",
            "lineageTag": "e8ea2b43-133e-46ea-a988-e6f654967cd0"
          },
          {
            "name": "Sales: Tooltip X measure",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR selectedX = SELECTEDVALUE( 'Param: Scatter X'[Order] )",
              "VAR xMeasure = ",
              "SWITCH(",
              "    selectedX,",
              "    0, [Tickets],",
              "    1, [Revenue],",
              "    2, [Discount],",
              "    3, [Profit]",
              ")",
              "VAR result = IF( ISBLANK( xMeasure ), 0, xMeasure )",
              "RETURN result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _SelectedMeasure = SELECTEDVALUE('Param: Scatter X'[Order])",
                "VAR _CurrentMeasure = SELECTEDMEASURE()",
                "VAR _Format = ",
                "IF(",
                "    _SelectedMeasure IN {1,2,3},",
                "    SWITCH(",
                "        TRUE(),",
                "        _CurrentMeasure < 1000, \"$0\",",
                "        _CurrentMeasure < 1000000, \"$#,#\",",
                "        _CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        _CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN _Format"
              ]
            },
            "lineageTag": "86797e82-925b-4b66-a0e1-60ca03146eab"
          },
          {
            "name": "Sales: Tooltip Y measure",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR selectedY = SELECTEDVALUE( 'Param: Scatter Y'[Order] )",
              "VAR yMeasure = ",
              "SWITCH(",
              "    selectedY,",
              "    0, [Tickets],",
              "    1, [Revenue],",
              "    2, [Discount],",
              "    3, [Profit]",
              ")",
              "VAR result = IF( ISBLANK( yMeasure ), 0, yMeasure )",
              "RETURN result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _SelectedMeasure = SELECTEDVALUE('Param: Scatter Y'[Order])",
                "VAR _CurrentMeasure = SELECTEDMEASURE()",
                "VAR _Format = ",
                "IF(",
                "    _SelectedMeasure IN {1,2,3},",
                "    SWITCH(",
                "        TRUE(),",
                "        _CurrentMeasure < 1000, \"$0\",",
                "        _CurrentMeasure < 1000000, \"$#,#\",",
                "        _CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        _CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN _Format"
              ]
            },
            "lineageTag": "b9379367-b6e3-45c7-bfd6-d21d72334797"
          },
          {
            "name": "Sales: Tooltip X Axis",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR maxDate = ",
              "CALCULATE(",
              "    MAXX(",
              "        ALLEXCEPT( 'Fact: Orders', 'Fact: Orders'[eventID] ),",
              "        MAX( 'Fact: Orders'[purchaseDateID] )",
              "    ),",
              "REMOVEFILTERS('Dim: Calendar')",
              ")",
              "",
              "VAR minDate = ",
              "CALCULATE(",
              "    MINX(",
              "        ALLEXCEPT( 'Fact: Orders', 'Fact: Orders'[eventID] ),",
              "        MIN( 'Fact: Orders'[purchaseDateID] )",
              "    ),",
              "REMOVEFILTERS('Dim: Calendar')",
              ")",
              "",
              "VAR selectedDate = CALCULATE( SELECTEDVALUE('Dim: Calendar'[dateID]))",
              "",
              "VAR result = CALCULATE( IF( selectedDate >= minDate && selectedDate <= maxDate, 1, 0) )",
              "",
              "RETURN result"
            ],
            "formatString": "0",
            "lineageTag": "ee3c8623-a558-4560-aef6-c8559063a8cc"
          },
          {
            "name": "Sales: Tooltip X Label",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR selectedX = SELECTEDVALUE( 'Param: Scatter X'[Order] )",
              "VAR xLabel = ",
              "SWITCH(",
              "    selectedX,",
              "    0, \"Tickets\",",
              "    1, \"Gross revenue\",",
              "    2, \"Discount\",",
              "    3, \"Profit\"",
              ")",
              "RETURN xLabel"
            ],
            "lineageTag": "f9989102-2322-4f63-8499-788d12b4f9ad"
          },
          {
            "name": "Sales: Tooltip Y Label",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR selectedY = SELECTEDVALUE( 'Param: Scatter Y'[Order] )",
              "VAR yLabel = ",
              "SWITCH(",
              "    selectedY,",
              "    0, \"Tickets\",",
              "    1, \"Gross revenue\",",
              "    2, \"Discount\",",
              "    3, \"Profit\"",
              ")",
              "RETURN yLabel"
            ],
            "lineageTag": "1ce5f3ee-aee3-4d01-9331-87945aecffe3"
          },
          {
            "name": "Sales: Tooltip Title",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "SELECTEDVALUE( 'Dim: Calendar'[monthLong] ) & \" \" & SELECTEDVALUE( 'Dim: Calendar'[year] )"
            ],
            "lineageTag": "399963c8-9c14-4b29-b1a3-95bb7a91ed7d"
          },
          {
            "name": "Sales: X % of Total by Events",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. Events analysis",
            "expression": [
              "",
              "VAR percentageByEvent = ",
              "CALCULATE(",
              "    DIVIDE(",
              "        [Sales: X Measure],",
              "        CALCULATE( [Sales: X Measure], ALLSELECTED( 'Dim: Events'[name] ) ),",
              "        0",
              "    )",
              ")",
              "VAR percentageByTicket = ",
              "CALCULATE(",
              "    DIVIDE(",
              "        [Sales: X Measure],",
              "        CALCULATE( [Sales: X Measure], ALLSELECTED( 'Dim: Tickets'[distance] ) ),",
              "        0",
              "    )",
              ")",
              "VAR result =",
              "SWITCH(",
              "    TRUE(),",
              "    ISINSCOPE( 'Dim: Tickets'[distance] ), percentageByTicket,",
              "    ISINSCOPE( 'Dim: Events'[name] ), percentageByEvent",
              ")",
              "RETURN result"
            ],
            "lineageTag": "a7b55165-1116-4158-8389-cb20f7362b40"
          },
          {
            "name": "Sales: Y % of Total by Events",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. Events analysis",
            "expression": [
              "",
              "VAR percentageByEvent = ",
              "CALCULATE(",
              "    DIVIDE(",
              "        [Sales: Y Measure],",
              "        CALCULATE( [Sales: Y Measure], ALLSELECTED( 'Dim: Events'[name] ) ),",
              "        0",
              "    )",
              ")",
              "VAR percentageByTicket = ",
              "CALCULATE(",
              "    DIVIDE(",
              "        [Sales: Y Measure],",
              "        CALCULATE( [Sales: Y Measure], ALLSELECTED( 'Dim: Tickets'[distance] ) ),",
              "        0",
              "    )",
              ")",
              "VAR result =",
              "SWITCH(",
              "    TRUE(),",
              "    ISINSCOPE( 'Dim: Tickets'[distance] ), percentageByTicket,",
              "    ISINSCOPE( 'Dim: Events'[name] ), percentageByEvent",
              ")",
              "RETURN result"
            ],
            "lineageTag": "7b689d83-e91d-435f-8efe-5382d69abb82"
          },
          {
            "name": "Sales: Y Measure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. Events analysis",
            "expression": [
              "",
              "VAR selectedY = SELECTEDVALUE( 'Param: Scatter Y'[Order] )",
              "VAR yMeasure = ",
              "SWITCH(",
              "    selectedY,",
              "    0, [Tickets],",
              "    1, [Revenue],",
              "    2, [Discount],",
              "    3, [Profit]",
              ")",
              "RETURN yMeasure"
            ],
            "lineageTag": "e2ab1cf8-817d-482c-a1df-c8176240ef36"
          },
          {
            "name": "Sales: X Measure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. Events analysis",
            "expression": [
              "",
              "VAR selectedX = SELECTEDVALUE( 'Param: Scatter X'[Order] )",
              "VAR xMeasure = ",
              "SWITCH(",
              "    selectedX,",
              "    0, [Tickets],",
              "    1, [Revenue],",
              "    2, [Discount],",
              "    3, [Profit]",
              ")",
              "RETURN xMeasure"
            ],
            "lineageTag": "dd208688-50b6-402c-9a6a-44f2a7bff350"
          },
          {
            "name": "Sales: Y constant line",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. Events analysis",
            "expression": [
              "",
              "MEDIANX( ALLSELECTED( 'Dim: Events'[name] ), [Sales: Y Measure] )"
            ],
            "lineageTag": "555fd472-dc52-4e94-a50f-568957452e14"
          },
          {
            "name": "Sales: Average Order Value of Selected Events",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4. Events analysis",
            "expression": [
              "",
              "AVERAGEX(",
              "    ALLSELECTED( 'Dim: Events'[name] ),",
              "    [AVG profit per Order]",
              ")"
            ],
            "lineageTag": "6f4378ad-9d63-467e-bc35-bcdbefa5362a"
          },
          {
            "name": "Sales: Tooltip Subtitle",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "SELECTEDVALUE( 'Dim: Events'[name] )"
            ],
            "lineageTag": "17a6a116-5ce7-45b1-b438-68f44d8f1682"
          },
          {
            "name": "Sales: Tooltip Cluster Label",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Scatter Cluster Color'[Order] ),",
              "    0, \" \",",
              "    1, \"Profit Margin %\",",
              "    2, \"AVG Order Value\"",
              ")"
            ],
            "lineageTag": "dc86e9a6-6765-4501-980e-373512eb4542"
          },
          {
            "name": "Sales: Tooltip Cluster Value",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR avgProfit =",
              "SWITCH(",
              "    TRUE(),",
              "    [AVG profit per Order] < 1000000, FORMAT([AVG profit per Order], \"$#,#\"),",
              "    [AVG profit per Order] < 1000000000, FORMAT([AVG profit per Order], \"$#,,.00M\"),",
              "    [AVG profit per Order] >= 1000000000, FORMAT([AVG profit per Order],\"$#,,,.00B\")",
              ")",
              "VAR avgProfitSelectedEvents = ",
              "CALCULATE(",
              "    AVERAGEX(",
              "        ALLSELECTED( 'Dim: Events'[name] ),",
              "        [AVG profit per Order]",
              "    ),",
              "REMOVEFILTERS( 'Dim: Events' )",
              ")",
              "VAR avgProfitSelectedEventsFormatted = ",
              "SWITCH(",
              "    TRUE(),",
              "    [Sales: Average Order Value of Selected Events] < 1000000, FORMAT(avgProfitSelectedEvents, \"$#,#\") ,",
              "    [Sales: Average Order Value of Selected Events] < 1000000000, FORMAT(avgProfitSelectedEvents, \"$#,,.00M\"),",
              "    [Sales: Average Order Value of Selected Events] >= 1000000000, FORMAT(avgProfitSelectedEvents, \"$#,,,.00B\")",
              ")",
              "VAR result = ",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Scatter Cluster Color'[Order] ),",
              "    0, BLANK(),",
              "    1, FORMAT( [Profit Margin], \"0%\" ),",
              "    2, avgProfit & \" vs \" & avgProfitSelectedEventsFormatted",
              ")",
              "RETURN result"
            ],
            "lineageTag": "adb89971-972d-4957-b6b4-40fefef81c31"
          },
          {
            "name": "Sales: Cluster Tooltip Title",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "IF( ",
              "    HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ),",
              "    FORMAT( SELECTEDVALUE( 'Dim: Calendar'[date]), \"dd MMM yyyy\"),",
              "    SELECTEDVALUE( 'Dim: Calendar'[monthLong] ) & \" \" & SELECTEDVALUE( 'Dim: Calendar'[year] )",
              ")"
            ],
            "lineageTag": "101f9ffc-5f2c-45d4-8a26-f7b686fd5e0e"
          },
          {
            "name": "Sales: Cluster Tooltip Label",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Sales metrics slicer'[order] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, \"Orders completed\",",
              "    2, \"Tickets sold\",",
              "    3, \"Gross sales revenue\",",
              "    4, \"Discount given\",",
              "    5, \"Net profit\"",
              ")",
              "RETURN result"
            ],
            "lineageTag": "0edc5612-e58e-49c0-afeb-30bd3a29b59f"
          },
          {
            "name": "Sales: Cluster Tooltip Reference 1",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "// Daily View",
              "VAR PD = ",
              "    CALCULATE(",
              "    [Sales: Dynamic],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, DAY ) ",
              "    )",
              "VAR dodChange = [Sales: Dynamic] - PD",
              "VAR PDFormatted = ",
              "IF(",
              "    SELECTEDVALUE('Param: Sales metrics slicer'[order]) IN {3,4,5},",
              "    SWITCH(",
              "        TRUE(),",
              "        dodChange < 1000000, FORMAT( dodChange, \"$#,#\"),",
              "        dodChange < 1000000000, FORMAT( dodChange, \"$#,,.00M\"),",
              "        dodChange >= 1000000000, FORMAT( dodChange, \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( dodChange, \"#,#\" )",
              ")",
              "VAR dodChangePerc = DIVIDE( DoDChange, PD, 0 )",
              "VAR dodDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    dodChangePerc > 0, \"▲ \" & FORMAT( dodChangePerc, \"0%\" ) & \" ( \" & PDFormatted & \")\",",
              "    dodChangePerc = 0, \"— \",",
              "    dodChangePerc < 0, \"▼ \" & FORMAT( ABS(dodChangePerc), \"0%\" ) & \" ( \" & PDFormatted & \")\"",
              ")",
              "",
              "// Monthly View",
              "VAR PM = ",
              "    CALCULATE(",
              "    [Sales: Dynamic],",
              "    DATEADD( 'Dim: Calendar'[date] , -1, MONTH ) ",
              "    )",
              "",
              "VAR momChange = [Sales: Dynamic] - PM",
              "VAR PMFormatted = ",
              "IF(",
              "    SELECTEDVALUE('Param: Sales metrics slicer'[order]) IN {3,4,5},",
              "    SWITCH(",
              "        TRUE(),",
              "        momChange < 1000000, FORMAT( momChange, \"$#,#\"),",
              "        momChange < 1000000000, FORMAT( momChange, \"$#,,.00M\"),",
              "        momChange >= 1000000000, FORMAT( momChange, \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( momChange, \"#,#\" )",
              ")",
              "VAR momChangePerc = DIVIDE( momChange, PM, 0 )",
              "VAR momDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    momChangePerc > 0, \"▲ \" & FORMAT( momChangePerc, \"0%\" ) & \" ( \" & PMFormatted & \")\",",
              "    momChangePerc = 0, \"— \",",
              "    momChangePerc < 0, \"▼ \" & FORMAT( ABS(momChangePerc), \"0%\" ) & \" ( \" & PMFormatted & \")\"",
              ")",
              "",
              "// Choose which measure to display",
              "VAR result = IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), dodDisplay, momDisplay )",
              "RETURN result"
            ],
            "lineageTag": "1b59b402-62b2-4d48-b6af-4afb102fae03"
          },
          {
            "name": "Sales: Cluster Tooltip Reference 2",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "// Daily View",
              "VAR dodChange = [Sales: Dynamic] - [Sales: Dynamic SPLY]",
              "VAR PDFormatted = ",
              "IF(",
              "    SELECTEDVALUE('Param: Sales metrics slicer'[order]) IN {3,4,5},",
              "    SWITCH(",
              "        TRUE(),",
              "        dodChange < 1000000, FORMAT( dodChange, \"$#,#\"),",
              "        dodChange < 1000000000, FORMAT( dodChange, \"$#,,.00M\"),",
              "        dodChange >= 1000000000, FORMAT( dodChange, \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( dodChange, \"#,#\" )",
              ")",
              "VAR dodChangePerc = DIVIDE( DoDChange, [Sales: Dynamic SPLY], 0 )",
              "VAR dodDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    dodChangePerc > 0, \"▲ \" & FORMAT( dodChangePerc, \"0%\" ) & \" ( \" & PDFormatted & \")\",",
              "    dodChangePerc = 0, \"— \",",
              "    dodChangePerc < 0, \"▼ \" & FORMAT( ABS(dodChangePerc), \"0%\" ) & \" ( \" & PDFormatted & \")\"",
              ")",
              "",
              "// Monthly View",
              "VAR momChange = [Sales: Dynamic] - [Sales: Dynamic SPLY]",
              "VAR PMFormatted = ",
              "IF(",
              "    SELECTEDVALUE('Param: Sales metrics slicer'[order]) IN {3,4,5},",
              "    SWITCH(",
              "        TRUE(),",
              "        momChange < 1000000, FORMAT( momChange, \"$#,#\"),",
              "        momChange < 1000000000, FORMAT( momChange, \"$#,,.00M\"),",
              "        momChange >= 1000000000, FORMAT( momChange, \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( momChange, \"#,#\" )",
              ")",
              "VAR momChangePerc = DIVIDE( momChange, [Sales: Dynamic SPLY], 0 )",
              "VAR momDisplay = ",
              "SWITCH(",
              "    TRUE(),",
              "    momChangePerc > 0, \"▲ \" & FORMAT( momChangePerc, \"0%\" ) & \" ( \" & PMFormatted & \")\",",
              "    momChangePerc = 0, \"— \",",
              "    momChangePerc < 0, \"▼ \" & FORMAT( ABS(momChangePerc), \"0%\" ) & \" ( \" & PMFormatted & \")\"",
              ")",
              "",
              "// Choose which measure to display",
              "VAR result = IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), dodDisplay, momDisplay )",
              "RETURN result"
            ],
            "lineageTag": "74cc783c-0c3f-481a-b034-8e3e96ceb87e"
          },
          {
            "name": "Sales: Cluster Tooltip Reference 3",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "// Daily View",
              "VAR CD = [Moving AVG by Day]",
              "VAR CDFormatted = ",
              "IF(",
              "    SELECTEDVALUE('Param: Sales metrics slicer'[order]) IN {3,4,5},",
              "    SWITCH(",
              "        TRUE(),",
              "        CD < 1000000, FORMAT( CD, \"$#,#\"),",
              "        CD < 1000000000, FORMAT( CD, \"$#,,.00M\"),",
              "        CD >= 1000000000, FORMAT( CD, \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( CD, \"#,#\" )",
              ")",
              "VAR dodDisplay = ",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Daily moving average'[order] ),",
              "    3, \"3-day moving average: \" & CDFormatted,",
              "    7, \"7-day moving average: \" & CDFormatted,",
              "    15, \"15-day moving average: \" & CDFormatted,",
              "    24, \"24-day moving average: \" & CDFormatted,",
              "    30, \"30-day moving average: \" & CDFormatted",
              ")",
              "",
              "// Monthly View",
              "VAR CM = [Moving AVG by Month]",
              "VAR CMFormatted = ",
              "IF(",
              "    SELECTEDVALUE('Param: Sales metrics slicer'[order]) IN {3,4,5},",
              "    SWITCH(",
              "        TRUE(),",
              "        CM < 1000000, FORMAT( CM, \"$#,#\"),",
              "        CM < 1000000000, FORMAT( CM, \"$#,,.00M\"),",
              "        CM >= 1000000000, FORMAT( CM, \"$#,,,.00B\")",
              "    ),",
              "    FORMAT( CM, \"#,#\" )",
              ")",
              "VAR momDisplay = ",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Monthly moving average'[order] ),",
              "    3, \"3-month moving average: \" & CMFormatted,",
              "    6, \"6-month moving average: \" & CMFormatted,",
              "    9, \"9-day moving average: \" & CMFormatted,",
              "    12, \"12-day moving average: \" & CMFormatted",
              ")",
              "",
              "// Choose which measure to display",
              "VAR result = IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), CDFormatted, CMFormatted )",
              "RETURN result"
            ],
            "lineageTag": "68b0320e-41dc-434a-8b60-65b207eb552a"
          },
          {
            "name": "Sales: Cluster Tooltip Reference 1 Title",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), \"vs PD:\" & REPT(UNICHAR(127),4), \"vs PM: \" & REPT(UNICHAR(127),6))"
            ],
            "lineageTag": "4a26ad1c-27a6-407b-97d8-690f387c24b6"
          },
          {
            "name": "Sales: Cluster Tooltip Reference 3 Title",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "// Daily View",
              "VAR dodDisplay = ",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Daily moving average'[order] ),",
              "    3, \"3-day MA: \",",
              "    7, \"7-day MA: \",",
              "    15, \"15-day MA: \",",
              "    24, \"24-day MA: \",",
              "    30, \"30-day MA: \"",
              ")",
              "",
              "// Monthly View",
              "VAR momDisplay = ",
              "SWITCH(",
              "    SELECTEDVALUE( 'Param: Monthly moving average'[order] ),",
              "    3, \"3-month MA: \",",
              "    6, \"6-month MA: \",",
              "    9, \"9-day MA: \",",
              "    12, \"12-day MA: \"",
              ")",
              "",
              "// Choose which measure to display",
              "VAR result = IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), dodDisplay, momDisplay )",
              "RETURN result"
            ],
            "lineageTag": "57eeeab4-cb6a-408b-81b3-3f5f24aa54e9"
          },
          {
            "name": "Sales: Cluster Tooltip Reference 2 Title",
            "displayFolder": "5. Tooltip",
            "expression": [
              "",
              "IF( HASONEFILTER( 'Dim: Calendar'[yearMonthLong] ), \"vs SPLY: \" & REPT( UNICHAR( 127 ), 2 ), \"vs SPLY: \" & REPT( UNICHAR( 127 ), 5 ) )"
            ],
            "lineageTag": "c243bd7a-a63b-418d-a2eb-2f64dea0eb27"
          }
        ],
        "partitions": [
          {
            "name": "3. Sales",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "4  Customers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "d6b0d794-3cce-4615-821b-364f82428a1c",
        "measures": [
          {
            "name": "New Users",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT( 'Dim: Customers'[id] ),",
              "    USERELATIONSHIP( 'Dim: Customers'[creationDateID], 'Dim: Calendar'[dateID] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a2267256-5224-46ec-aae5-c60e672bb1c1"
          },
          {
            "name": "New Users who purchased",
            "expression": [
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1",
              ")",
              "",
              "VAR NewUsers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Dim: Customers'[id] ),",
              "    USERELATIONSHIP( 'Dim: Customers'[creationDateID], 'Dim: Calendar'[dateID] )",
              ")",
              "",
              "VAR Purchasers =",
              "INTERSECT( CurrentCustomers, NewUsers )",
              "",
              "RETURN COUNTROWS( Purchasers )"
            ],
            "formatString": "0",
            "lineageTag": "05fc79b9-39f3-4d40-8f0c-7cf70a818fef"
          },
          {
            "name": "Summary: by Female Customers",
            "expression": [
              "",
              "CALCULATE( [Summary: Dynamic], 'Dim: Customers'[gender] = \"Female\" )"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR SelectedMeasure = SELECTEDVALUE('Param: Summary Metrics'[Group])",
                "VAR CurrentMeasure = SELECTEDMEASURE()",
                "VAR Result = ",
                "IF(",
                "    SelectedMeasure IN {3,4},",
                "    SWITCH(",
                "        TRUE(),",
                "        // _CurrentMeasure < 1000, \"$0\",",
                "        CurrentMeasure < 1000000, \"$#,#\",",
                "        CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN Result"
              ]
            },
            "lineageTag": "6120c5cd-3f30-41d6-8cce-fed484173d2e"
          },
          {
            "name": "Summary: by Male Customers",
            "expression": [
              "",
              "CALCULATE( [Summary: Dynamic], 'Dim: Customers'[gender] = \"Male\" )"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR SelectedMeasure = SELECTEDVALUE('Param: Summary Metrics'[Group])",
                "VAR CurrentMeasure = SELECTEDMEASURE()",
                "VAR Result = ",
                "IF(",
                "    SelectedMeasure IN {3,4},",
                "    SWITCH(",
                "        TRUE(),",
                "        // _CurrentMeasure < 1000, \"$0\",",
                "        CurrentMeasure < 1000000, \"$#,#\",",
                "        CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN Result"
              ]
            },
            "lineageTag": "c00add17-4ffc-464e-8d6a-660af43c8e53"
          }
        ],
        "partitions": [
          {
            "name": "4  Customers",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "1. Core Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "6c290237-0ace-421e-9e78-2193065f88d3",
        "measures": [
          {
            "name": "Complete Orders",
            "displayFolder": "1. Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS( ",
              "        FILTER(",
              "            'Fact: Orders',",
              "            'Fact: Orders'[orderStatus] = 1",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "c016b2b6-eca1-4593-a40d-b928d157a58f"
          },
          {
            "name": "Completion Rate",
            "displayFolder": "1. Orders",
            "expression": [
              "",
              "DIVIDE( [Complete Orders], [Total Orders], 0 )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1b4eaa3c-0e89-4b5b-9d96-a89f3d6a9e10"
          },
          {
            "name": "Total Orders",
            "displayFolder": "1. Orders",
            "expression": [
              "",
              "COUNTROWS( 'Fact: Orders' )"
            ],
            "formatString": "0",
            "lineageTag": "3755567f-cd75-44f4-937c-0afcf351f872"
          },
          {
            "name": "% of Target",
            "displayFolder": "2. Tickets",
            "expression": [
              "",
              "VAR maxDate = CALCULATE( MAX( 'Fact: Orders'[purchaseDateID] ), REMOVEFILTERS() )",
              "VAR maxDateInFilter = CALCULATE( MAX( 'Dim: Calendar'[dateID] ), 'Dim: Calendar'[dateID] <= maxDate )",
              "VAR percentageOfTotal = ",
              "IF(",
              "    MIN( 'Dim: Calendar'[dateID] ) <= maxDate,",
              "    CALCULATE(",
              "        [Tickets],",
              "        'Dim: Calendar'[dateID] <= maxDate",
              "    )",
              ")",
              "VAR result = DIVIDE( percentageOfTotal, SELECTEDVALUE( 'Dim: Events'[target] ) )",
              "RETURN IF( NOT ISBLANK( [Summary: Dynamic] ), result )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "066de0ba-446d-46d5-91ba-b9c0e97a53e2"
          },
          {
            "name": "Tickets",
            "displayFolder": "2. Tickets",
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(",
              "        'Fact: Orders',",
              "        'Fact: Orders'[totalTickets]",
              "    ),",
              "'Fact: Orders'[orderStatus] = 1",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "db01c5bd-a427-4391-868f-689b3322aeba"
          },
          {
            "name": "AVG Tickets per Order",
            "displayFolder": "2. Tickets",
            "expression": [
              "",
              "DIVIDE( [Tickets], [Complete Orders], 0 )"
            ],
            "formatString": "0",
            "lineageTag": "e419e402-3c73-4999-901a-c89ba5d3e6e5"
          },
          {
            "name": "Profit",
            "displayFolder": "3. Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(",
              "        'Fact: Orders',",
              "        ('Fact: Orders'[totalTickets] * 'Fact: Orders'[price]) - ('Fact: Orders'[totalTickets] * 'Fact: Orders'[price] * 'Fact: Orders'[discount])",
              "    ),",
              "'Fact: Orders'[orderStatus] = 1",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0afd203e-f5fa-46f9-bf39-feb6ff36b6ea"
          },
          {
            "name": "Profit Margin",
            "displayFolder": "3. Profit",
            "expression": [
              "",
              "DIVIDE( [Profit], [Revenue] )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "18d52035-765a-4438-be18-1bf0dd1885b3"
          },
          {
            "name": "New Customers",
            "displayFolder": "4. Customers",
            "expression": [
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] )",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' ),",
              "    REMOVEFILTERS( 'Dim: Tickets' )",
              ")",
              "",
              "VAR NewCustomers = ",
              "EXCEPT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result = COUNTROWS( NewCustomers )",
              "",
              "RETURN Result"
            ],
            "formatString": "#,0",
            "lineageTag": "f3394efe-04d9-4974-9ce5-f513911041fb"
          },
          {
            "name": "Repeat Customers",
            "displayFolder": "4. Customers",
            "expression": [
              "",
              "VAR CurrentCustomers = ",
              "CALCULATETABLE( ",
              "    VALUES( 'Fact: Orders'[customerID] ), ",
              "    'Fact: Orders'[orderStatus] = 1, ",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ) ",
              ")",
              "",
              "VAR PastCustomers = ",
              "CALCULATETABLE(",
              "    VALUES( 'Fact: Orders'[customerID] ),",
              "    'Fact: Orders'[orderStatus] = 1,",
              "    NOT ISBLANK( 'Fact: Orders'[creationDateID] ),",
              "    FILTER( ",
              "        ALL( 'Dim: Calendar' ),",
              "        'Dim: Calendar'[dateID] < MIN( 'Fact: Orders'[creationDateID] ) ",
              "    ),",
              "    REMOVEFILTERS( 'Dim: Events' ),",
              "    REMOVEFILTERS( 'Dim: Tickets' )",
              ")",
              "",
              "VAR RepeatCustomers = ",
              "INTERSECT( CurrentCustomers, PastCustomers )",
              "",
              "VAR Result = COUNTROWS( RepeatCustomers )",
              "",
              "RETURN Result"
            ],
            "formatString": "0",
            "lineageTag": "e6a54961-9f19-41aa-92b0-93822246631f"
          },
          {
            "name": "Total Customers",
            "displayFolder": "4. Customers",
            "expression": [
              "",
              "COUNTROWS(",
              "    CALCULATETABLE(",
              "        VALUES( 'Fact: Orders'[customerID] ),",
              "        'Fact: Orders'[orderStatus] = 1,",
              "        NOT ISBLANK( 'Fact: Orders'[creationDateID] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3f814892-aaec-42b6-9d74-ae5c5af286bb"
          },
          {
            "name": "Discount",
            "displayFolder": "5. Discount",
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(",
              "        'Fact: Orders',",
              "        'Fact: Orders'[totalTickets] * 'Fact: Orders'[price] * 'Fact: Orders'[discount]",
              "    ),",
              "'Fact: Orders'[orderStatus] = 1",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a99b623f-774b-4036-b352-07bf1ecea268"
          },
          {
            "name": "Discount: AVG % per Order",
            "displayFolder": "5. Discount",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGEX(",
              "        'Fact: Orders',",
              "        'Fact: Orders'[discount]",
              "    ),",
              "    'Fact: Orders'[orderStatus] = 1",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "bacc9a6b-f12e-40be-acc3-8118b47f5d57"
          },
          {
            "name": "Revenue",
            "displayFolder": "6. Revenue",
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(",
              "        'Fact: Orders',",
              "        'Fact: Orders'[totalTickets] * 'Fact: Orders'[price]",
              "    ),",
              "'Fact: Orders'[orderStatus] = 1",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e3d61a3c-d4b5-4808-a882-421fe36326b6"
          },
          {
            "name": "Summary: Dynamic",
            "displayFolder": "8. Dynamic",
            "expression": [
              "",
              "VAR selectedParam = SELECTEDVALUE( 'Param: Summary Metrics Slicer'[Group] )",
              "VAR result = ",
              "SWITCH(",
              "    selectedParam,",
              "    1, [Complete Orders],",
              "    2, [Tickets],",
              "    3, [Discount],",
              "    4, [Profit]",
              ")",
              "RETURN result"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _SelectedMeasure = SELECTEDVALUE('Param: Summary Metrics'[Group])",
                "VAR _CurrentMeasure = SELECTEDMEASURE()",
                "VAR _Format = ",
                "IF(",
                "    _SelectedMeasure IN {3,4},",
                "    SWITCH(",
                "        TRUE(),",
                "        // _CurrentMeasure < 1000, \"$0\",",
                "        _CurrentMeasure < 1000000, \"$#,#\",",
                "        _CurrentMeasure < 1000000000, \"$#,,.00M\",",
                "        _CurrentMeasure >= 1000000000, \"$#,,,.00B\"",
                "    ),",
                "    \"#,#\"",
                ")",
                "RETURN _Format"
              ]
            },
            "lineageTag": "af70cfa8-6d56-42b1-b0f3-10cf95d519f5"
          },
          {
            "name": "AVG order per customer",
            "displayFolder": "1. Orders",
            "expression": [
              "",
              "ROUNDUP( DIVIDE( [Total Orders], [Total Customers], 0 ), 0 )"
            ],
            "formatString": "0",
            "lineageTag": "0bd10958-70fd-42b9-9ffd-11c04f338b43"
          },
          {
            "name": "AVG revenue per order",
            "displayFolder": "6. Revenue",
            "expression": [
              "",
              "DIVIDE( [Revenue], [Complete Orders] , 0 )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "758b23ae-5e4b-4dec-889e-5f184ffe3f27"
          },
          {
            "name": "Discount: AVG value per Order",
            "displayFolder": "5. Discount",
            "expression": [
              "",
              "DIVIDE( [Discount], [Complete Orders], 0 )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c3254bf5-aed1-4ff4-93e5-3caab172eade"
          },
          {
            "name": "Last Refresh",
            "displayFolder": "9. General",
            "expression": [
              "",
              "FORMAT( LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[purchaseDateID] ) ), \"dd-mm-yyyy\" )"
            ],
            "lineageTag": "83055c45-e251-4753-b383-1518cd3100d3"
          },
          {
            "name": "AVG profit per Order",
            "displayFolder": "3. Profit",
            "expression": [
              "",
              "DIVIDE( [Profit], [Complete Orders], 0 )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "87ace6e9-9b72-43ae-ae94-42ea1c051242"
          },
          {
            "name": "AVG Tickets Value",
            "displayFolder": "2. Tickets",
            "expression": [
              "",
              "DIVIDE( [Profit], [Tickets], 0 )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e49eab5a-487a-426e-82ed-0f8a957c4302"
          },
          {
            "name": "AVG Discount Value",
            "displayFolder": "5. Discount",
            "expression": [
              "",
              "DIVIDE( [Discount], [Complete Orders] )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7437cad8-5d06-4705-98f1-797dc7a7ab79"
          },
          {
            "name": "Last DOS",
            "displayFolder": "9. General",
            "expression": [
              "",
              "\"Last date of sales: \" & FORMAT( LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[creationDateID] ) ), \"dd-mm-yyyy\" )"
            ],
            "lineageTag": "a7d97a16-07ba-4671-b1e6-2b1f3b8423e0"
          },
          {
            "name": "Current date range",
            "displayFolder": "9. General",
            "expression": [
              "",
              "\"Current date range: Last \" & SELECTEDVALUE( 'Param: Day Period Slicer'[Period] ) ",
              "& \" | Between \"",
              "& FORMAT( LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MIN( 'Fact: Orders'[creationDateID] ) ), \"dd-mm-yyyy\" )",
              "& \" and \"",
              "& FORMAT( LOOKUPVALUE( 'Dim: Calendar'[date], 'Dim: Calendar'[dateID], MAX( 'Fact: Orders'[creationDateID] ) ), \"dd-mm-yyyy\" )"
            ],
            "lineageTag": "51f1b244-a92b-4334-83e0-7f522c0657ba"
          },
          {
            "name": "Daily view",
            "displayFolder": "9. General",
            "expression": [
              "",
              "\"Daily view of \" & SELECTEDVALUE( 'Dim: Calendar'[monthLong] ) & \" \" & SELECTEDVALUE( 'Dim: Calendar'[year] ) "
            ],
            "lineageTag": "f94358c3-1d2d-43de-aa92-91f1e0d75c2e"
          },
          {
            "name": "Monthy view",
            "displayFolder": "9. General",
            "expression": [
              "",
              "\"Monthly view of \" & SELECTEDVALUE( 'Dim: Calendar'[year] )"
            ],
            "lineageTag": "4dec5b65-348d-4973-b7ce-fd842d01bbfe"
          }
        ],
        "partitions": [
          {
            "name": "1. Core Measures",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Param: Daily moving average",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1d3cf392-9a51-408d-ba4d-b18114615f98",
            "sortByColumn": "order",
            "sourceColumn": "period",
            "summarizeBy": "none"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f745dfc8-b281-404d-b644-f1af0e58147e",
            "sourceColumn": "order",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "3073f865-f935-46dc-8e2f-109c17972d25",
        "partitions": [
          {
            "name": "Param: Daily moving average",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlZISawsVtJRMlaK1YlWModxzcFcQ1MY39AULGBkAhMwMgELGBvADTBQio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [period = _t, order = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"period\", type text}, {\"order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Param: Sales metrics",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d31c2e9669294622a1ff075d76e18111"
          }
        ],
        "columns": [
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "c9d384c7-be9f-47f7-976b-f925626f4283",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "field"
                }
              ]
            },
            "sortByColumn": "order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "67207a9f-ff13-48c6-9489-062ceadb1dd0",
            "sortByColumn": "order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f8cadd84-15c0-48f2-935c-a2f6f96d7802",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "fe3f1186-6582-435d-ba2b-255713756da6",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "isVisible",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "3579fa61-6c70-404d-a090-105029546b57",
            "sourceColumn": "[Value5]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "a3d0f3be-9eda-42d0-8938-0f7b07cb0c3c",
        "partitions": [
          {
            "name": "Param: Sales metrics",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    // Orders",
                "    (\"Completed orders\", NAMEOF('1. Core Measures'[Complete Orders]), 1, 1, 1),",
                "    (\"vs PM %\", NAMEOF([Sales: MoM Change %]), 2, 1, 0),",
                "    (\"Completion rate\", NAMEOF('1. Core Measures'[Completion Rate]), 3, 1, 0),",
                "",
                "    // Tickets",
                "    (\"Tickets sold\", NAMEOF('1. Core Measures'[Tickets]), 4, 2, 1),",
                "    (\"vs PM %\", NAMEOF([Sales: MoM Change %]), 5, 2, 0),",
                "    (\"AVG / Order\", NAMEOF('1. Core Measures'[AVG Tickets per Order]), 6, 2, 0),",
                "",
                "    // Revenue",
                "    (\"Sales revenue\", NAMEOF('1. Core Measures'[Revenue]), 7, 3, 1),",
                "    (\"vs PM %\", NAMEOF([Sales: MoM Change %]), 8, 3, 0),",
                "    (\"AVG / Order\", NAMEOF('1. Core Measures'[AVG revenue per order]), 9, 3, 0),",
                "",
                "    // Discount",
                "    (\"Discount\", NAMEOF('1. Core Measures'[Discount]), 10, 4, 1),",
                "    (\"vs PM %\", NAMEOF([Sales: MoM Change %]), 11, 4, 0),",
                "    (\"AVG / Order\", NAMEOF('1. Core Measures'[Discount: AVG value per Order]), 12, 4, 0),",
                "",
                "    // Profit",
                "    (\"Profit\", NAMEOF('1. Core Measures'[Profit]), 13, 5, 1),",
                "    (\"vs PM %\", NAMEOF([Sales: MoM Change %]), 14, 5, 0),",
                "    (\"Margin %\", NAMEOF('1. Core Measures'[Profit Margin]), 15, 5, 0)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Param: Sales metrics slicer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2caf6d8e-275c-4b79-b43a-2c569086dab1",
            "sortByColumn": "order",
            "sourceColumn": "group",
            "summarizeBy": "none"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6f4803d1-a765-4975-a6b6-b95f970f9baf",
            "sourceColumn": "order",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "c3655908-7bcb-4d61-b996-780159e2fc3d",
        "partitions": [
          {
            "name": "Param: Sales metrics slicer",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Hcg7DoAgDADQq5DOLP5OoAcw0Y0wGKgJEalpwfOLjO8ZAzPdT8SMXhF7ZAENHVhtYA/uwixKKPqafcvtiCiK8cVUsO7QdgniqKRcY2yxMp3h5wTWfg==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [group = _t, order = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"group\", type text}, {\"order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Param: Monthly moving average",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0dd3743e-b173-40f9-a3be-d6acc27f149b",
            "sortByColumn": "order",
            "sourceColumn": "period",
            "summarizeBy": "none"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9c8c8fba-a3ab-4a6d-8780-7235deb0c73f",
            "sourceColumn": "order",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "7ae1f649-e41a-4e38-97d5-75e7028d0016",
        "partitions": [
          {
            "name": "Param: Monthly moving average",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlbIzc8ryShW0lEyVorViVYyQwiYgQUsEQKWYAFDI4SIoZFSbCwA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [period = _t, order = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"period\", type text}, {\"order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim: Ticket phase",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "phaseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe74d451-5e11-44d7-9271-276b93366535",
            "sourceColumn": "phaseID",
            "summarizeBy": "none"
          },
          {
            "name": "phase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7ff9599-7435-4084-8fae-08aeafadd917",
            "sortByColumn": "phaseID",
            "sourceColumn": "phase",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "68dd11d8-1930-4ebd-8af3-2d48c70d825c",
        "partitions": [
          {
            "name": "Dim: Ticket phase",
            "mode": "import",
            "queryGroup": "Dimension tables",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\dev\\activeTix\\data\\bi\\tickets.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"\", Int64.Type}, {\"ticket_id\", Int64.Type}, {\"event_id\", Int64.Type}, {\"distance\", type text}, {\"phase_id\", Int64.Type}, {\"price\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"ticket_id\", \"id\"}, {\"event_id\", \"eventID\"}, {\"phase_id\", \"phaseID\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"phaseID\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"phase\", each if [phaseID] = 1 then \"Super Early Bird\" else if [phaseID] = 2 then \"Early Bird\" else if [phaseID] = 3 then \"Standard\" else if [phaseID] = 4 then \"Late\" else \"Others\")",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Param: Scatter X",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0d3e66ca47164504b8cad69e7f55dcd7"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f4a8575c-5d72-4788-9364-a634bb2b133e",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Field"
                }
              ]
            },
            "sortByColumn": "Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "87152716-dba2-4027-85d7-e9356571c757",
            "sortByColumn": "Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f9c0ac04-81f7-4f3c-a829-3831868690f9",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "e8096f0e-a360-416f-9051-fce7395e6d76",
        "partitions": [
          {
            "name": "Param: Scatter X",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Tickets\", NAMEOF('1. Core Measures'[Tickets]), 0),",
                "    (\"Gross revenue\", NAMEOF('1. Core Measures'[Revenue]), 1),",
                "    (\"Discount\", NAMEOF('1. Core Measures'[Discount]), 2),",
                "    (\"Profit\", NAMEOF('1. Core Measures'[Profit]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Param: Scatter Y",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "814ccc65bfe94f8593bc851242ea2676"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7bb76d08-f564-44d4-8269-2a907b7f3570",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Field"
                }
              ]
            },
            "sortByColumn": "Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f8a75e3d-5821-4b02-8505-b550aa37b47d",
            "sortByColumn": "Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "cff8c7c8-d80b-41ce-aa53-22c9643e8a8f",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "91468137-20dd-4068-b6cd-ee9ef3de266b",
        "partitions": [
          {
            "name": "Param: Scatter Y",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Tickets\", NAMEOF('1. Core Measures'[Tickets]), 0),",
                "    (\"Gross revenue\", NAMEOF('1. Core Measures'[Revenue]), 1),",
                "    (\"Discount\", NAMEOF('1. Core Measures'[Discount]), 2),",
                "    (\"Profit\", NAMEOF('1. Core Measures'[Profit]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Param: Scatter size",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "14bf1e5da9604c769f2e105d5cace8aa"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "424ce262-388a-43c0-96c8-785ad5babab9",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Field"
                }
              ]
            },
            "sortByColumn": "Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "34314e2f-883a-466d-b19e-4447983d66c7",
            "sortByColumn": "Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "2bb6b458-e343-4674-9661-f8077f2739b8",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "54a7426e-02be-4253-9535-d4a88f84daf1",
        "partitions": [
          {
            "name": "Param: Scatter size",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Tickets\", NAMEOF('1. Core Measures'[Tickets]), 0),",
                "    (\"Gross revenue\", NAMEOF('1. Core Measures'[Revenue]), 1),",
                "    (\"Discount\", NAMEOF('1. Core Measures'[Discount]), 2),",
                "    (\"Profit\", NAMEOF('1. Core Measures'[Profit]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Param: Scatter Cluster Color",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Option",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b4a89ef1-bdf7-44ea-bc51-137b296b8986",
            "sourceColumn": "Option",
            "summarizeBy": "none"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "953b6401-2868-455a-8371-a52c3ba712ee",
            "sourceColumn": "Order",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "762df857-a570-4949-9699-46d6f9442496",
        "partitions": [
          {
            "name": "Param: Scatter Cluster Color",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcklNSyzNKVHSUTJQitWJVvJNLErPzFNQBQoYggX8i1JSixTCEnNKUxXKihUcw9yBUkZKsbEA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Option = _t, Order = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Option\", type text}, {\"Order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Param: Scatter Legends",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "cluster",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "afb599df-705c-456e-a9a7-b8276f59cd7d",
            "sourceColumn": "cluster",
            "summarizeBy": "none"
          },
          {
            "name": "segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1c8218a6-7706-41c6-add6-9ae2731538b4",
            "sortByColumn": "segmentID",
            "sourceColumn": "segment",
            "summarizeBy": "none"
          },
          {
            "name": "segmentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f635976e-7c40-498a-99e3-689f476c89a6",
            "sourceColumn": "segmentID",
            "summarizeBy": "count"
          }
        ],
        "isHidden": true,
        "lineageTag": "7e9451ce-2975-4c30-b545-76630a9b2e59",
        "partitions": [
          {
            "name": "Param: Scatter Legends",
            "mode": "import",
            "queryGroup": "Parameters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlDSUXJJTUsszSkBsgyUYnWilQyBrJhSAwPjVFsFCwNVIM8QLm5moKqgq2BmCRI1QlWdrGAGVmwMFjZCMsQxzB3IM0EVT4YKmyrFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [cluster = _t, segment = _t, segmentID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"cluster\", Int64.Type}, {\"segment\", type text}, {\"segmentID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}